datam = [{id: "m5", name: "Bubbly", desc: "For participating in 10 Group Chats", n: 40941},
{id: "m43", name: "Bundled", desc: "For participating in Group Chat", n: 909098},
{id: "m47", name: "Group Carer", desc: "For participating in 75 Group Chats", n: 9963},
{id: "m45", name: "Group Chatter", desc: "For participating in 20 Group Chats", n: 24835},
{id: "m44", name: "Group Chimer", desc: "For participating in 5 Group Chats", n: 69607},
{id: "m176", name: "Group Friend", desc: "For completing 1 group support chat", n: 71099},
{id: "m48", name: "Group Healer", desc: "For participating in 100 Group Chats", n: 8152},
{id: "m57", name: "Group Support Oath", desc: "For taking the 7 Cups Group Support member oath", n: 532},
{id: "m46", name: "Group Supporter", desc: "For participating in 50 Group Chats", n: 13147},
{id: "m277", name: "Sharing Circle I", desc: "For participating in a Sharing Circle session 7 days in a row", n: 122},
{id: "m278", name: "Sharing Circle II", desc: "For participating in a Sharing Circle session 30 days in a row", n: 18},
{id: "m279", name: "Sharing Circle III", desc: "For participating in a Sharing Circle session 90 days in a row", n: 0},
{id: "m280", name: "Sharing Circle IV", desc: "For participating in a Sharing Circle session 180 days in a row", n: 0},
{id: "m281", name: "Sharing Circle V", desc: "For participating in a Sharing Circle session 365 days in a row", n: 0},
{id: "m211", name: "Traveler", desc: "For teens who have recently aged up.", n: 3},
{id: "m160", name: "Workshop: Cool as Cucumbe", desc: "For workshop subscribers", n: 0},
{id: "m134", name: "1000 Day Streak", desc: "For completing a step on the Growth path for 1,000 consecutive days", n: 0},
{id: "m112", name: "12 Steps", desc: "For completion of the 12 Step Working Guide", n: 329},
{id: "m125", name: "14 Day Streak", desc: "For completing a step on the Growth path for 14 consecutive days", n: 1127},
{id: "m128", name: "180 Day Streak", desc: "For completing a step on the Growth path for 180 consecutive days", n: 20},
{id: "m129", name: "260 Day Streak", desc: "For completing a step on the Growth path for 260 consecutive days", n: 13},
{id: "m126", name: "30 Day Streak", desc: "For completing a step on the Growth path for 30 consecutive days", n: 474},
{id: "m130", name: "365 Day Streak", desc: "For completing a step on the Growth path for 365 consecutive days", n: 10},
{id: "m131", name: "500 Day Streak", desc: "For completing a step on the Growth path for 500 consecutive days", n: 1},
{id: "m132", name: "625 Day Streak", desc: "For completing a step on the Growth path for 625 consecutive days", n: 4},
{id: "m124", name: "7 Day Streak", desc: "For completing a step on the Growth path for 7 consecutive days", n: 4324},
{id: "m110", name: "7Cups Guide", desc: "For completing the 7 Cups for the Searching Soul eBook", n: 431},
{id: "m133", name: "800 Day Streak", desc: "For completing a step on the Growth path for 800 consecutive days", n: 0},
{id: "m127", name: "90 Day Streak", desc: "For completing a step on the Growth path for 90 consecutive days", n: 96},
{id: "m61", name: "ADHD", desc: "For completion of the Attention-Deficit/Hyperactivity Disorder Course", n: 905},
{id: "m81", name: "Alcohol & Drug Abuse", desc: "For completion of the Alcohol & Drug Course", n: 376},
{id: "m73", name: "Anxiety", desc: "For completion of the Anxiety Course", n: 3586},
{id: "m64", name: "Boundaries", desc: "For completion of the Boundaries Couse", n: 754},
{id: "m83", name: "Bullying", desc: "For completion of the Bullying Course", n: 409},
{id: "m148", name: "Champion Self-Esteem", desc: "For completing 30 days of a Self Esteem Challenge", n: 13},
{id: "m84", name: "Chronic Pain", desc: "For completion of the Chronic Pain Course", n: 254},
{id: "m87", name: "College Guide", desc: "For completion of the College Guide Course", n: 511},
{id: "m95", name: "Compassion Hero", desc: "For members who have successfully completed the group support compassion course", n: 532},
{id: "m74", name: "Depression", desc: "For completion of the Depression Course", n: 1895},
{id: "m188", name: "Diabetes CBT", desc: "For completion of the Diabetes CBT Guide", n: 58},
{id: "m179", name: "Diary Study", desc: "For those who participate in the teen diary study", n: 5},
{id: "m75", name: "Eating Disorders", desc: "For completion of the Eating Disorders Course", n: 1052},
{id: "m146", name: "Entrepreneur Self-Esteem", desc: "For completing 10 days of a Self-esteem Challenge", n: 55},
{id: "m90", name: "Exercise Motivation", desc: "For completion of the Exercise Motivation Course", n: 538},
{id: "m85", name: "Family Stress", desc: "For completion of the Family Stress Course", n: 630},
{id: "m65", name: "Forgiveness", desc: "For completion of the Forgiveness Course", n: 371},
{id: "m70", name: "Getting Unstuck", desc: "For completion of the Getting Unstuck Course", n: 1139},
{id: "m66", name: "Grief", desc: "For completion of the Grief Course", n: 591},
{id: "m154", name: "Holiday Kindness", desc: "For members who reconnect with a listener during the holidays", n: 22},
{id: "m215", name: "Hope Training", desc: "For completion of the Hope Training Guide", n: 164},
{id: "m224", name: "Kindness Challenge", desc: "For completing a Kindness Challenge", n: 80},
{id: "m88", name: "Loneliness Guide", desc: "For completion of the Loneliness Guide Course", n: 934},
{id: "m67", name: "Managing Bipolar", desc: "For completion of the Managing Bipolar Course", n: 612},
{id: "m68", name: "Managing Finances", desc: "For completion of the Managing Finances Course", n: 387},
{id: "m147", name: "Master Self-Esteem", desc: "For completing 20 days of a self-esteem Challenge", n: 46},
{id: "m244", name: "New Mom Support Group", desc: "For completing the New Moms support guide", n: 57},
{id: "m63", name: "OCD", desc: "For completion of the Obsessive-Compulsive Disorder Course", n: 437},
{id: "m76", name: "Panic Attacks", desc: "For completion of the Panic Attacks Course", n: 516},
{id: "m82", name: "Parenting", desc: "For completion of the Parenting Course", n: 208},
{id: "m227", name: "Peer Pro", desc: "For completing all 12 of the SAMHSA Trainings", n: 0},
{id: "m228", name: "Peer Training 1", desc: "For completing Session 1 of the SAMHSA Training", n: 4},
{id: "m237", name: "Peer Training 10", desc: "For completing Session 10 of the SAMHSA Training", n: 1},
{id: "m238", name: "Peer Training 11", desc: "For completing Session 11 of the SAMHSA Training", n: 1},
{id: "m239", name: "Peer Training 12", desc: "For completing Session 12 of the SAMHSA Training", n: 1},
{id: "m229", name: "Peer Training 2", desc: "For completing Session 2 of the SAMHSA Training", n: 1},
{id: "m230", name: "Peer Training 3", desc: "For completing Session 3 of the SAMHSA Training", n: 1},
{id: "m231", name: "Peer Training 4", desc: "For completing Session 4 of the SAMHSA Training", n: 1},
{id: "m232", name: "Peer Training 5", desc: "For completing Session 5 of the SAMHSA Training", n: 1},
{id: "m233", name: "Peer Training 6", desc: "For completing Session 6 of the SAMHSA Training", n: 1},
{id: "m234", name: "Peer Training 7", desc: "For completing Session 7 of the SAMHSA Training", n: 1},
{id: "m235", name: "Peer Training 8", desc: "For completing Session 8 of the SAMHSA Training", n: 1},
{id: "m236", name: "Peer Training 9", desc: "For completing Session 9 of the SAMHSA Training", n: 1},
{id: "m59", name: "People of Color Guide", desc: "For completion of the Young People of Color Course", n: 266},
{id: "m92", name: "Perinatal", desc: "For completion of the Perinatal Mood Disorder Course", n: 108},
{id: "m93", name: "Schizophrenia", desc: "For completion of the Coping with Schizophrenia Course", n: 311},
{id: "m80", name: "Self Harm", desc: "For completion of the Self Harm Course", n: 2637},
{id: "m86", name: "Sleeping Well", desc: "For completion of the Sleeping Well Course", n: 604},
{id: "m62", name: "Social Anxiety", desc: "For completion of the Social Anxiety Course", n: 1579},
{id: "m274", name: "Soul Searcher", desc: "For reading and reviewing the 7 Cups for the Searching Soul book", n: 21},
{id: "m91", name: "Startup Support", desc: "For completion of the Startup Support Course", n: 299},
{id: "m121", name: "Strike-a-Streak", desc: "For members who are committed to taking 1 step on their growth path every day and sharing their growth path successes with the community!", n: 350},
{id: "m77", name: "Surviving Breakups", desc: "For completion of the Surviving Breakups Course", n: 2138},
{id: "m69", name: "Surviving Domestic Assaul", desc: "For completion of the Surviving Domestic Assault Course", n: 490},
{id: "m89", name: "Test Anxiety", desc: "For completion of the Test Anxiety Course", n: 477},
{id: "m78", name: "Traumatic Experiences", desc: "For completion of the Traumatic Experiences Course", n: 979},
{id: "m187", name: "Weight Management", desc: "For completion of the Weight Management Guide", n: 152},
{id: "m79", name: "Work Related Stress", desc: "For completion of the Work Related Stress Course", n: 334},
{id: "m137", name: "3rd Bday Hug-a-Friend", desc: "For sending an appreciative shout-out to someone in the community who has made a positive impact on you in the feed, forum or 1-1 message", n: 31},
{id: "m136", name: "3rd Birthday Milestone", desc: "For sharing your personal milestones as a listener over the past year!", n: 27},
{id: "m207", name: "50+", desc: "For dedication to supporting those in the 50 & Over Community", n: 0},
{id: "m203", name: "5th Birthday Party", desc: "For those who participated in events for 7 Cups 5th Birthday!", n: 77},
{id: "m250", name: "7 Cups DJ", desc: "For those who DJ in the music rooms", n: 0},
{id: "m266", name: "7Cups Culture", desc: "For taking 7Cups Culture Guide Test", n: 0},
{id: "m140", name: "7CupsGO!", desc: "For completing the 7 Cups Go community challenge", n: 19},
{id: "m263", name: "7th Birthday Party", desc: "For participating in the 7 Cups 7th birthday celebration", n: 11},
{id: "m216", name: "Accountability", desc: "For completing an accountability challenge", n: 16},
{id: "m201", name: "Addiction Support", desc: "For dedication to supporting those in the Addiction Support Community", n: 0},
{id: "m222", name: "All for One", desc: "For showing good teamwork", n: 0},
{id: "m34", name: "Appreciated Voice", desc: "For receiving 20 Forum post upvotes", n: 6429},
{id: "m161", name: "Appreciation Buddy", desc: "For participating in a self-care practice 3 times a week for 1 month", n: 2},
{id: "m243", name: "Approved Discussion Group", desc: "For approved access to the Depression Guided Support", n: 0},
{id: "m245", name: "BeKind21", desc: "For participating in the #BeKind21 event", n: 45},
{id: "m195", name: "Bipolar Support", desc: "For dedication to supporting those in the Bipolar Disorder Support Community", n: 0},
{id: "m225", name: "Black History Month 2019", desc: "For participating in a Black History Month event in 2019", n: 3},
{id: "m221", name: "Bridging Community", desc: "For participating in both discussions and forums of a Subcommunity", n: 0},
{id: "m213", name: "Busy Bee", desc: "For those who display exemplary collaboration skills across multiple teams", n: 1},
{id: "m200", name: "Caregivers Support", desc: "For dedication to supporting those in the Caregivers Support Community", n: 0},
{id: "m37", name: "Collaborator", desc: "For receiving 100 Forum post upvotes", n: 1200},
{id: "m36", name: "Community", desc: "For receiving 50 Forum post upvotes", n: 2426},
{id: "m261", name: "Community & Special Event", desc: "For participation in events across 7 Cups", n: 19},
{id: "m260", name: "Community Builder", desc: "For successfully completing the 7 Cups Community building course", n: 5},
{id: "m35", name: "Contributor", desc: "For receiving 25 Forum post upvotes", n: 5093},
{id: "m115", name: "Cup Connect", desc: "For spreading the word about 7 Cups to help make the world a better place", n: 146},
{id: "m253", name: "Cupsmas 2019", desc: "For participating in Cupsmas 2019 Events", n: 10},
{id: "m31", name: "Debuted", desc: "For posting an introduction in the Forum", n: 17236},
{id: "m251", name: "DJ Team", desc: "For being on the Music Therapy team", n: 3},
{id: "m208", name: "Eating Disorder Support", desc: "For dedication to supporting those in the Eating Disorder Support Community", n: 0},
{id: "m111", name: "Einstein", desc: "For work on an original idea that advances the community", n: 13},
{id: "m165", name: "Evolution", desc: "For users who join 7 Cups as a teen and continue using 7 Cups as an adult", n: 41958},
{id: "m180", name: "Fall 2017 Events", desc: "For participating in special events on 7 Cups in the Fall of 2017", n: 95},
{id: "m206", name: "Fall 2018 Events", desc: "For those who participated in an event in Fall 2018", n: 499},
{id: "m265", name: "Fall Events 2020", desc: "For participating in 2020 fall events", n: 0},
{id: "m219", name: "Familiar Face", desc: "For spending time interacting in a Subcommunity", n: 18},
{id: "m117", name: "Feeders", desc: "For those dedicated to feeding the feed", n: 12},
{id: "m38", name: "First Compassion", desc: "For receiving the first Compassion Heart", n: 7043},
{id: "m30", name: "First Post", desc: "For creating the first Forum Post", n: 243590},
{id: "m170", name: "Flower Crown", desc: "For actively participating in the appreciation festival", n: 128},
{id: "m98", name: "Forum Buddy", desc: "For making 100 forum posts after earning the Meet & Greet badge", n: 876},
{id: "m96", name: "Forum Companion", desc: "For making 25 forum posts and 5 upvotes", n: 3042},
{id: "m177", name: "Forum Friend", desc: "For posting to the forum 3 times", n: 31767},
{id: "m99", name: "Forum Guide", desc: "For making 250 forum posts after earning the Meet & Greet badge", n: 367},
{id: "m97", name: "Forum Helper", desc: "For making 50 forum posts after earning the Meet & Greet badge", n: 1604},
{id: "m100", name: "Forum Light", desc: "For making 500 forum posts after earning the Meet & Greet badge", n: 202},
{id: "m72", name: "Forum Supporter", desc: "For Members who offer dedicated support in the public forums", n: 34},
{id: "m209", name: "Foster Care", desc: "For dedication to supporting those in the Foster Care Support Community", n: 0},
{id: "m107", name: "Friendly Face", desc: "For completing 100 group chats and earning 300 compassion hearts", n: 7449},
{id: "m183", name: "GlitterStar", desc: "For winners of a Creative Challenge during the Holidays", n: 37},
{id: "m113", name: "Hangout Key", desc: "For access to the Member Hangout room", n: 320},
{id: "m158", name: "Healthy Hearts", desc: "For participating in Heart Disease Awareness Month", n: 14},
{id: "m39", name: "Helpful heart", desc: "For earning 50 Compassion Hearts", n: 72444},
{id: "m108", name: "Helping Hand", desc: "For completing 200 group chats and earning 600 compassion hearts", n: 4515},
{id: "m33", name: "Helping out", desc: "For receiving 5 Forum post upvotes", n: 32748},
{id: "m259", name: "Host", desc: "For hosting group support discussions/fun events", n: 0},
{id: "m142", name: "Icebreaker Champion", desc: "For participating in an icebreaker challenge", n: 54},
{id: "m214", name: "Joiner", desc: "For taking the first steps to get involved in your subcommunity", n: 102},
{id: "m220", name: "Kindness Crusader", desc: "For spreading kindness on 7 Cups", n: 26},
{id: "m40", name: "Kindness personified", desc: "For earning 100 Compassion Hearts", n: 35727},
{id: "m157", name: "Love Monster", desc: "For community members who send the most appreciation in a month!", n: 3},
{id: "m41", name: "Loving Soul", desc: "For earning 200 Compassion Hearts", n: 18701},
{id: "m123", name: "Maisie", desc: "For sharing “Game of Thrones” star Maisie’s Anti-bullying campaign with your personal network", n: 69},
{id: "m58", name: "Marathon", desc: "For completing a difficult challenge on 7 Cups to help build the community", n: 120},
{id: "m190", name: "Meaghan's Heart", desc: "For members who earn 150 compassion hearts", n: 16955},
{id: "m171", name: "Meet & Greet", desc: "For welcoming new members and listeners in the intro forums", n: 23892},
{id: "m143", name: "Mega Member", desc: "For showing initiative and dedication to the 7 Cups community", n: 13},
{id: "m116", name: "Member Support Room Guide", desc: "For a leader in the member community dedicated to welcoming new members in group support chatrooms", n: 12},
{id: "m94", name: "Milestone Team", desc: "For members and listeners who have opted to provide support to those sharing milestones", n: 5},
{id: "m167", name: "NAMI Messenger", desc: "For people to share how they told someone at 7 Cups about the NAMI community and/or NAMI resources", n: 31},
{id: "m164", name: "NAMI Oath", desc: "For taking the NAMI Community Oath and dedicating yourself to the NAMI community on 7 Cu", n: 62},
{id: "m255", name: "Needs Reply Team", desc: "For forum team members focused on \"Needs Reply\" queue", n: 0},
{id: "m144", name: "Olympic Rings", desc: "For participating in an Olympic Challenge", n: 0},
{id: "m194", name: "Parenting & Pregnancy", desc: "For dedication to supporting those in the Parenting & Pregnancy Community", n: 0},
{id: "m198", name: "Peppermint", desc: "For being an active member of the 7 Cups Welcome Committee", n: 434},
{id: "m152", name: "Pink Ribbon", desc: "For participating in a Breast Cancer Awareness activity", n: 18},
{id: "m284", name: "Pop-Up Ninja", desc: "For leading 3+ pop-up discussions in 1 week. Like a ninja.", n: 1},
{id: "m191", name: "Positivity Challenge", desc: "For participating in a Positivity Challenge on 7 Cups", n: 33},
{id: "m193", name: "Positivity Support", desc: "For dedication to supporting those in the Motivation & Self-Help Community", n: 0},
{id: "m226", name: "Purposeful Parent", desc: "For participating in a parenting-related event", n: 0},
{id: "m32", name: "Reaching out", desc: "For first creating the first Forum Thread", n: 91054},
{id: "m159", name: "Ready for Change", desc: "For Change group workshop participants", n: 0},
{id: "m218", name: "Resolution Ruler", desc: "For participating in a resolution event", n: 8},
{id: "m217", name: "Santa's Helper", desc: "For participating in a holiday event", n: 10},
{id: "m254", name: "Santapaws 2019", desc: "For coming in first in one of the Santapaws 2019 competition categories!", n: 0},
{id: "m223", name: "SC Cupsiversary", desc: "For participating in a Subcommunity anniversary event", n: 0},
{id: "m184", name: "Self-Harm Support Team", desc: "For dedication to supporting those in Self-Harm Recovery Community", n: 0},
{id: "m258", name: "Sharing Circle", desc: "For leading sharing circles", n: 7},
{id: "m196", name: "Spring Events", desc: "For those who participated in a Spring event.", n: 26},
{id: "m141", name: "Strangers Unite", desc: "For sharing the “Talk to Strangers’ page with your personal network", n: 98},
{id: "m257", name: "Subcommunity Rockstar", desc: "For showing dedication, consistency and excellence as a sub-community team member", n: 1},
{id: "m197", name: "Summer Events", desc: "For those who participated in a Summer event.", n: 388},
{id: "m163", name: "Summer Events 2017", desc: "For participating in a special event organized by your subcommunity during the summer of 2017", n: 28},
{id: "m248", name: "Support Key", desc: "For access to LGBTQ+ and Disability group support rooms", n: 542},
{id: "m106", name: "Supportive Smile", desc: "For completing 50 group chats and earning 150 compassion hearts", n: 11971},
{id: "m175", name: "Teammate", desc: "For joining your first subcommunity", n: 59508},
{id: "m202", name: "Teen Zone Support Team", desc: "For dedication to supporting those in the Teen Zone Community", n: 0},
{id: "m205", name: "Translation Master", desc: "For translating 500+ terms to help bring 7 Cups to all people", n: 4},
{id: "m204", name: "Translation Microscope", desc: "For helping to proofread and edit translated terms within the Translation Project", n: 0},
{id: "m262", name: "Translation Pro", desc: "For translating 1000+ terms to help bring 7 Cups to all people", n: 2},
{id: "m139", name: "Translator", desc: "For taking the lead to bring 7 cups of tea to another country and translating the site into the native language", n: 121},
{id: "m185", name: "Trauma Support Team", desc: "For dedication to supporting those in Trauma Support Community", n: 0},
{id: "m114", name: "TS Key", desc: "For access to the Thinking Space room", n: 3030},
{id: "m192", name: "Wiki Team", desc: "For anyone who signs helps support the 7 Cups wiki", n: 8},
{id: "m186", name: "Winter 2018 Special Event", desc: "For community members that participated in a winter 2018 event", n: 49},
{id: "m252", name: "Winter Events", desc: "For those who participated in a Winter event", n: 21},
{id: "m109", name: "Wise One", desc: "For completing 500 group chats and earning 1500 compassion hearts", n: 2178},
{id: "m135", name: "3rd Birthday Star", desc: "For sharing your referral link in honor of 7 Cups’ 3rd Birthday", n: 25},
{id: "m20", name: "Care Messenger", desc: "For having a personal referral URL visited by 100 different people", n: 16},
{id: "m17", name: "Got your Back", desc: "For having a personal referral URL visited by 5 different people", n: 495},
{id: "m21", name: "Hobnob", desc: "For refrerring 5 new Members to 7 Cups of Tea", n: 29},
{id: "m16", name: "Lifting Up", desc: "For the first click received to personal referral URL", n: 4808},
{id: "m150", name: "MedX", desc: "For feeling proud and spreading the news that 7 Cups won the Stanford MedX Prize for Health Care Systems Design!", n: 65},
{id: "m19", name: "Open Arms", desc: "For having a personal referral URL visited by 50 different people", n: 46},
{id: "m169", name: "Social Butterfly", desc: "For being a committed soldier spreading the word about 7cups for 3 consecutive months!", n: 0},
{id: "m168", name: "Social Soldier", desc: "For uniforming up and dedicating time to reach out to people in need of support for 1 month!", n: 0},
{id: "m18", name: "Strong Support", desc: "For having a personal referral URL visited by 20 different people", n: 115},
{id: "m275", name: "Super Supporter", desc: "For following 7 Cups on a social media platform", n: 36},
{id: "m6", name: "Chief Chat", desc: "For completing the first conversation", n: 2336},
{id: "m8", name: "Confident Voice", desc: "For leaving text reviews for 5 Listeners", n: 68348},
{id: "m122", name: "Hello Again", desc: "For reconnecting with an old listener and saying hello!", n: 390},
{id: "m7", name: "Honest Voice", desc: "For leaving the first text review for a Listener", n: 929483},
{id: "m12", name: "Journeying Strong", desc: "For sending 1,000 messages to Listeners", n: 62191},
{id: "m2", name: "Linked", desc: "For connecting with a Listener or a Therapist for the first time", n: 5376},
{id: "m11", name: "Milestone", desc: "For sending 500 messages to Listeners", n: 114417},
{id: "m9", name: "Power Voice", desc: "For leaving text reviews for 10 Listeners", n: 28342},
{id: "m3", name: "Quintet", desc: "For connecting with 5 Listeners", n: 944849},
{id: "m13", name: "Reconnect", desc: "For completing a second conversation with the same Listener", n: 1229},
{id: "m155", name: "Sponsee", desc: "For members who work with a listener sponsor", n: 87},
{id: "m15", name: "Strong Bond", desc: "For completing 100 conversations with the same Listener", n: 11700},
{id: "m249", name: "Strong Bond I", desc: "For completing a chat with 5 different listeners", n: 1048},
{id: "m172", name: "Strong Bond II", desc: "For completing 10 chats each with 10 different listeners", n: 4354},
{id: "m173", name: "Strong Bond III", desc: "For completing 25 chats each with 10 different listeners", n: 968},
{id: "m174", name: "Strong Bond IV", desc: "For completing 50 chats with 20 different listeners", n: 53},
{id: "m10", name: "Strong Start", desc: "For sending 100 messages to Listeners", n: 558594},
{id: "m4", name: "Super Active", desc: "For connecting with 15 Listeners", n: 162348},
{id: "m166", name: "Togetherness", desc: "For completing 50 chats with the same listener", n: 14210},
{id: "m14", name: "Walking Together", desc: "For completing 25 conversations with the same Listener", n: 48668},
{id: "m1", name: "Hand Shake", desc: "For signing up to become a Member", n: NaN},
{id: "m56", name: "Member Oath", desc: "For taking the 7 Cups member oath", n: 4618},
{id: "m156", name: "Newbie", desc: "For being a new member less than 4 weeks", n: 51748},
{id: "m269", name: "Becoming a Leader", desc: "For completing Course 2 of the Leadership Development Program", n: 2},
{id: "m151", name: "Country Champion", desc: "For spreading the word about 7 Cups in your country & being a leader for your country community on and off of 7 Cups", n: 0},
{id: "m149", name: "Country Leader", desc: "For on-site community builders, helping to build country communities at 7 Cups", n: 0},
{id: "m240", name: "Editorial Assistant", desc: "For being a member of the content volunteer team", n: 10},
{id: "m182", name: "Forum Flag Team", desc: "For members of the forum flag team", n: 2},
{id: "m145", name: "Forum Member Leader", desc: "For a member who has been selected to help moderate & support the 7 Cups public forums", n: 5},
{id: "m212", name: "Forum Member Project Lead", desc: "For a member who is a project leader in the forums", n: 1},
{id: "m199", name: "General Support Team", desc: "For dedication to supporting those in the General Support Community", n: 0},
{id: "m272", name: "Leadership Graduate", desc: "For listeners who have successfully completed the Leadership Development Program", n: 0},
{id: "m270", name: "Leadership Principles", desc: "For completing Course 4 of the Leadership Development Program", n: 0},
{id: "m271", name: "Leadership Trainee", desc: "For members currently enrolled in Leadership Development Program", n: 7},
{id: "m241", name: "Marketing Assistant", desc: "For being a member of the marketing volunteer team", n: 4},
{id: "m267", name: "Personal Leadership 101", desc: "For completing Course 1 of the Leadership Development Program", n: 2},
{id: "m268", name: "Personal Leadership 102", desc: "For completing Course 3 of the Leadership Development Program", n: 0},
{id: "m178", name: "Q & A Glitter Trotter", desc: "For members of the Q & A approval team", n: 3},
{id: "m181", name: "Question Crew", desc: "For members of the Q & A team that help with question approvals", n: 1},
{id: "m189", name: "SC Forum Mentor", desc: "For forum mentors who focuse exclusively in their Subcommunity", n: 0},
{id: "m153", name: "Training Badge", desc: "For access to special leadership training rooms", n: 0},
{id: "m242", name: "Writer", desc: "For being a writer on the content volunteer team", n: 17}]

datal = [{id: "l179", name: "Active Listening", desc: "For completion of the Mock Chat portion of initial listener training", n: 320377},
{id: "l174", name: "Affirmative", desc: "For completing the first step in becoming a listener", n: 844093},
{id: "l176", name: "Chat & Text", desc: "For completing Active Listening Chat & Text portion of initial listener training", n: 311209},
{id: "l73", name: "Jump Start", desc: "For early dedication to the 7 Cups of Tea by completing 25 conversations in the first week", n: 71207},
{id: "l86", name: "Listener Oath", desc: "For taking the 7 Cups of Tea Listener Oath", n: 28548},
{id: "l177", name: "Listening Ace", desc: "For completing the entire Active Listening Course portion of initial listener training", n: 494106},
{id: "l57", name: "Newbie", desc: "For being a new listener less than 1 month", n: 124368},
{id: "l175", name: "Reflection", desc: "For completing the Active Listening Reflection portion of initial listener training", n: 324943},
{id: "l141", name: "11-2-14", desc: "For those who helped during the 11/2/2014 surge", n: 1536},
{id: "l12", name: "First Responder", desc: "For sending 100+ messages after “on-call” signal is sent out asking for listeners to sign on", n: 64},
{id: "l96", name: "Holiday Helper", desc: "For sending 300+ messages on holidays when asked to lend extra support", n: 60},
{id: "l427", name: "Accountability", desc: "For completing an accountability challenge", n: 204},
{id: "l313", name: "Anonymous Eval Team", desc: "For mentors who participates on the anon eval team", n: 20},
{id: "l207", name: "Award Winning Mod", desc: "For earning a special, distinctive award for hard work and dedication to Group Support and the moderator role", n: 12},
{id: "l68", name: "Baron of Big-Hearts", desc: "For receiving 100 positive text reviews from members", n: 1306},
{id: "l66", name: "Clerk of Bear Hugs", desc: "For receiving 25 positive text reviews from members", n: 13979},
{id: "l479", name: "Continuing Education", desc: "For holding yourself in a professional manner and continuing to excel and self-educate", n: 3924},
{id: "l411", name: "Gratitude Abound", desc: "For receiving 10 positive text reviews from members", n: 13370},
{id: "l65", name: "Jester of Smiles", desc: "For receiving 8 positive text reviews from members", n: 47034},
{id: "l69", name: "Knight of Smilehood", desc: "For receiving 200 positive text reviews from members", n: 264},
{id: "l30", name: "Listening Ear", desc: "For completing 90+ conversations within 1 month", n: 44767},
{id: "l31", name: "Long Ears", desc: "For completing 300+ conversations within 3 months", n: 14478},
{id: "l324", name: "Loyal Friend", desc: "For first approved positive text review from a member", n: 192153},
{id: "l280", name: "Mock Chat Master", desc: "For successfully completing 5 mock chats to improve your listening skills. Nominated by 5 listeners who do the mock chats with you.", n: 57},
{id: "l67", name: "Piper of Dedication", desc: "For receiving 50 positive text reviews from members", n: 4845},
{id: "l135", name: "Quality Champion", desc: "For verifying 25 other listeners through the Verified Listener process", n: 89},
{id: "l172", name: "Quality Guru", desc: "For verifying 50 other listeners through the Verified Listener process", n: 68},
{id: "l136", name: "Refresher", desc: "For updating active listening skills with a practice mock chat", n: 33471},
{id: "l410", name: "Thankful Heart", desc: "For receiving 5 positive text reviews from members", n: 26371},
{id: "l487", name: "Tulip", desc: "For being an exceptional Listener", n: 216},
{id: "l121", name: "Verified Listener", desc: "For Listeners who have been verified by a Listener Mentor", n: 10742},
{id: "l286", name: "35+ Support", desc: "For dedication to supporting those in the 7 Cups 35+ Community.", n: 15},
{id: "l407", name: "Addiction Support", desc: "For dedication to supporting those in the Addiction Support Community", n: 7},
{id: "l133", name: "Ally", desc: "For providing support & information to 2 members with issues regarding sexuality or gender roles", n: 149},
{id: "l414", name: "Appreciated", desc: "For becoming eligible and unlocking free premium paths for a chosen member", n: 566},
{id: "l143", name: "Aviator", desc: "For helping 10 members achieve a personal victory", n: 29},
{id: "l406", name: "Caregivers Support", desc: "For dedication to supporting those in the Caregivers Support Community", n: 2},
{id: "l36", name: "Copilot", desc: "For helping 6 members achieve a personal victory", n: 49},
{id: "l337", name: "Fellow Friend", desc: "For completing 25 1-on-1 chats as a listener", n: 113660},
{id: "l377", name: "First Chat", desc: "For making it to one chat with a member", n: 180515},
{id: "l38", name: "Got Your Back", desc: "For honoring appointments with 10 members", n: 57},
{id: "l37", name: "Heart Healer", desc: "For supporting 2 members through a difficult romantic issue or relationship problem", n: 283},
{id: "l25", name: "Honor", desc: "For offering strong support to 2 military or veteran members", n: 115},
{id: "l35", name: "Kind Shoulder", desc: "For supporting 2 members through loss or grief", n: 197},
{id: "l32", name: "Magnet", desc: "For having more than 50 unique members or guests connect in one month", n: 52800},
{id: "l352", name: "Mediator Mod", desc: "For handling a difficult situation in a support room", n: 97},
{id: "l33", name: "Milestone", desc: "For helping 2 members achieve a personal victory", n: 235},
{id: "l353", name: "Mod Siren", desc: "For responding to the group support emergency form 20 times", n: 217},
{id: "l354", name: "Mod Squad", desc: "For providing back-up to another mod in a support room", n: 70},
{id: "l382", name: "Open Door", desc: "For completing 5 1-on-1 chats", n: 134947},
{id: "l58", name: "PenPal", desc: "For sending more than 10,000 messages to members or guests", n: 8603},
{id: "l142", name: "Pillar of Strength", desc: "For helping 4 members achieve a personal victory", n: 51},
{id: "l285", name: "Positivity Corner Support", desc: "For dedication to supporting those in the Positivity Corner support room.", n: 29},
{id: "l368", name: "Proudly Proactive I", desc: "For sending a private message welcoming 5 new members", n: 3127},
{id: "l369", name: "Proudly Proactive II", desc: "For sending a private message welcoming 15 new members", n: 1196},
{id: "l370", name: "Proudly Proactive III", desc: "For sending a private message welcoming 30 new members", n: 581},
{id: "l371", name: "Proudly Proactive IV", desc: "For sending a private message welcoming 50 new members", n: 341},
{id: "l372", name: "Proudly Proactive V", desc: "For sending a private message welcoming 100 new members", n: 172},
{id: "l422", name: "Receptionist", desc: "For assisting newly aged up teens.", n: 2},
{id: "l373", name: "Reconnection Hero I", desc: "For completing 5 chats each with 10 different members", n: 19101},
{id: "l374", name: "Reconnection Hero II", desc: "For completing 20 chats each with 10 different members", n: 2395},
{id: "l375", name: "Reconnection Hero III", desc: "For completing 50 chats with 20 different members", n: 110},
{id: "l504", name: "Sharing Circle I", desc: "For participating in a Sharing Circle session 7 days in a row", n: 50},
{id: "l505", name: "Sharing Circle II", desc: "For participating in a Sharing Circle session 30 days in a row", n: 8},
{id: "l506", name: "Sharing Circle III", desc: "For participating in a Sharing Circle session 90 days in a row", n: 0},
{id: "l507", name: "Sharing Circle IV", desc: "For participating in a Sharing Circle session 180 days in a row", n: 0},
{id: "l508", name: "Sharing Circle V", desc: "For participating in a Sharing Circle session 365 days in a row", n: 0},
{id: "l334", name: "Sponsor", desc: "For listeners who support at least one member as a sponsor", n: 70},
{id: "l360", name: "Steadfast Soul I", desc: "For completing 5 chats with the same member", n: 87744},
{id: "l361", name: "Steadfast Soul II", desc: "For completing 20 chats with the same member", n: 24777},
{id: "l362", name: "Steadfast Soul III", desc: "For completing 50 chats with the same member", n: 11188},
{id: "l284", name: "SYS Support", desc: "For dedication to supporting those in the 7 Cups Depression", n: 4},
{id: "l87", name: "Teen", desc: "For Adult Listeners who have chosen to be available for teens", n: 69},
{id: "l408", name: "Teen Zone Support Team", desc: "For dedication to supporting those in the Teen Zone Community", n: 9},
{id: "l34", name: "Warm Heart", desc: "For supporting 2 caregivers of people with intellectual disabilities", n: 152},
{id: "l336", name: "Welcoming Warrior", desc: "For listeners who welcome 50 members to 7 cups every week!", n: 13},
{id: "l137", name: "Appreciation Buddy", desc: "For being an Appreciation Team Member", n: 275},
{id: "l222", name: "Discussion Trainer", desc: "For training and supporting new group discussion leaders", n: 15},
{id: "l39", name: "Encourager", desc: "For being nominated by 10 other listeners as extra encouraging", n: 101},
{id: "l436", name: "Listener Discussion Leader", desc: "For those who lead Listener Discussions", n: 21},
{id: "l40", name: "Master Encourager", desc: "For being nominated by 50 other listeners as extra encouraging", n: 3},
{id: "l98", name: "Peer Support", desc: "For providing support to fellow Listeners", n: 113},
{id: "l42", name: "Peppermint", desc: "For being an active member of the 7 Cups Welcome Committee", n: 6495},
{id: "l85", name: "Peter Pan", desc: "For assisting Teen Listeners with acclimating to 7 Cups of Tea", n: 307},
{id: "l43", name: "Sage", desc: "For earning 25 upvotes on a single forum post", n: 577},
{id: "l297", name: "Twinning", desc: "For listener who have a listener twin & accountability partner", n: 1},
{id: "l303", name: "2nd Birthday Party", desc: "For participating in the 7 Cups 2nd Birthday Party!", n: 4174},
{id: "l301", name: "3rd Bday Hug-a-friend", desc: "For sending an appreciative shout-out to someone in the community who has made a positive impact on you in the feed, forum or 1-1 message", n: 137},
{id: "l300", name: "3rd Birthday Milestone", desc: "For sharing your personal milestones as a listener over the past year!", n: 98},
{id: "l417", name: "50+", desc: "For dedication to supporting those in the 50 & Over Community", n: 5},
{id: "l409", name: "5th Birthday Party", desc: "For those who participated in events for 7 Cups 5th Birthday!", n: 111},
{id: "l470", name: "7 Cups DJ", desc: "For those who DJ in the music rooms", n: 1},
{id: "l500", name: "7Cups Culture", desc: "For taking 7Cups Culture Guide Test", n: 0},
{id: "l306", name: "7CupsGO!", desc: "For completing the 7 Cups Go community challenge?", n: 31},
{id: "l496", name: "7th Birthday Party", desc: "For participating in the 7 Cups 7th birthday celebration!", n: 88},
{id: "l420", name: "Addiction Support", desc: "For dedication to supporting those in the Addiction Support Community", n: 1},
{id: "l434", name: "All for One", desc: "For showing good teamwork", n: 63},
{id: "l196", name: "Anxiety Support", desc: "For dedication to supporting those in the 7 Cups Anxiety Community", n: 76},
{id: "l459", name: "Approved Discussion Group 1", desc: "For approved access to the Depression Guided Support", n: 0},
{id: "l113", name: "Aristotle", desc: "For active participation in community discussions", n: 819},
{id: "l462", name: "BeKind21", desc: "For participating in the #BeKind21 event", n: 79},
{id: "l148", name: "Big Chat", desc: "For sending 5,000+ messages in a listener chatroom", n: 1039},
{id: "l401", name: "Bipolar Support", desc: "For dedication to supporting those in the Bipolar Disorder Support Community", n: 12},
{id: "l438", name: "Black History Month 2019", desc: "For participating in a Black History Month event in 2019", n: 10},
{id: "l433", name: "Bridging Community", desc: "For participating in both discussions and forums of a Subcommunity", n: 6},
{id: "l424", name: "Busy Bee", desc: "For those who display exemplary collaboration skills across multiple teams", n: 179},
{id: "l147", name: "Chit Chat", desc: "For sending 2,500+ messages in a listener chatroom", n: 1570},
{id: "l151", name: "Communicator", desc: "For making 250+ forum posts", n: 642},
{id: "l484", name: "Community & Special Events", desc: "For participation in events across 7 Cups", n: 105},
{id: "l186", name: "Community Builder", desc: "For leading 24+ chat room discussions", n: 196},
{id: "l333", name: "Connection Corner", desc: "For listeners & therapists who want to share & build community together", n: 827},
{id: "l184", name: "Conversationalist", desc: "For leading 4+ chat room discussions", n: 222},
{id: "l478", name: "COVID-19 Support", desc: "For dedication to supporting the "COVID-19 Room"", n: 0},
{id: "l473", name: "Cupsmas 2019", desc: "For participating in Cupsmas 2019 Events", n: 24},
{id: "l225", name: "Disability Support", desc: "For dedication to supporting those in the 7 Cups Disability Community", n: 15},
{id: "l471", name: "DJ Team", desc: "For being on the Music Therapy team", n: 28},
{id: "l418", name: "Eating Disorder Support", desc: "For dedication to supporting those in the Eating Disorder Support Community", n: 9},
{id: "l131", name: "Einstein", desc: "For work on an original idea that advances the community", n: 50},
{id: "l71", name: "Ellen", desc: "For earning 100+ compassion hearts in a day", n: 51734},
{id: "l258", name: "End of Year Award", desc: "For winning a prize in the End of Year Celebration week", n: 8},
{id: "l268", name: "Enthusiast", desc: "For being an active member of the teen discussion team", n: 26},
{id: "l195", name: "Events Team", desc: "For helping to organise events in the support rooms", n: 34},
{id: "l357", name: "Evolution", desc: "For users who join 7 Cups as a teen and continue using 7 Cups as an adult", n: 25854},
{id: "l385", name: "Fall 2017 Events", desc: "For participating in special events on 7 Cups in the Fall of 2017", n: 82},
{id: "l415", name: "Fall 2018 Events", desc: "For those who participated in an event in Fall 2018", n: 499},
{id: "l501", name: "Fall Events 2020", desc: "For participating in 2020 fall events", n: 56},
{id: "l431", name: "Familiar Face", desc: "For spending time interacting in a Subcommunity", n: 136},
{id: "l224", name: "Family Support", desc: "For dedication to supporting those in the 7 Cups Parenting Community", n: 24},
{id: "l421", name: "Feeder", desc: "For those dedicated to feeding the feed", n: 5},
{id: "l376", name: "First Community", desc: "For joining your first subcommunity", n: 29814},
{id: "l378", name: "First Post", desc: "For making your first post to the forum", n: 41917},
{id: "l156", name: "Florence Nightingale", desc: "For sending 10,000+ messages in a Group Support Chatroom", n: 610},
{id: "l296", name: "Flower Crown", desc: "For actively participating in the appreciation festival", n: 40},
{id: "l227", name: "Fly Swatter", desc: "For submitting a bug report that resulted in an improvement to the 7 Cups website", n: 24},
{id: "l89", name: "Forum Supporter", desc: "For offering support in a forum category that you would like to help build a community in", n: 39},
{id: "l132", name: "Forumpedia", desc: "For consistently providing relevant forum threads & resources in the chatroom", n: 250},
{id: "l419", name: "Foster Care", desc: "For dedication to supporting those in the Foster Care Support Community", n: 2},
{id: "l173", name: "Gamer Outreach", desc: "For care and support of the gamers community", n: 197},
{id: "l389", name: "GlitterStar", desc: "For winners of a Creative Challenge during the Holidays", n: 76},
{id: "l279", name: "Glowing Star", desc: "For successfully completing the various challenges during Quality Week.", n: 12},
{id: "l139", name: "Group Mod", desc: "For moderating the Group Support Chatrooms", n: 32},
{id: "l183", name: "Guest Host", desc: "For leading a chatroom discussion", n: 521},
{id: "l187", name: "Guiding Spirit", desc: "For leading 100+ chat room discussions", n: 42},
{id: "l287", name: "Hangout Key", desc: "For access to the Member Hangout room", n: 217},
{id: "l338", name: "Healthy Hearts", desc: "For participating in Heart Disease Awareness Month", n: 37},
{id: "l252", name: "Hello Again", desc: "For participating in the hello again campaign by checking in on my members", n: 763},
{id: "l380", name: "High 5", desc: "For making 5 posts in the forum", n: 11427},
{id: "l482", name: "Host", desc: "For hosting group support discussions/fun events", n: 14},
{id: "l308", name: "Icebreaker Champion", desc: "For participating in an icebreaker challenge", n: 290},
{id: "l425", name: "Joiner", desc: "For taking the first steps to get involved in your subcommunity", n: 409},
{id: "l432", name: "Kindness Crusader", desc: "For spreading kindness on 7 Cups", n: 85},
{id: "l197", name: "LGBTQ+ Support", desc: "For dedication to supporting those in the 7 Cups LGBTQ Community", n: 38},
{id: "l144", name: "Light Chat", desc: "For sending 200+ messages in a listener chatroom", n: 7534},
{id: "l130", name: "Love Bug", desc: "For earning 50+ compassion hearts in a day", n: 129119},
{id: "l335", name: "Love Monster", desc: "For community members who send the most appreciation in a month!", n: 33},
{id: "l295", name: "Maisie", desc: "For sharing “Game of Thrones” star Maisie’s Anti-bullying campaign with your personal network", n: 151},
{id: "l232", name: "Marathon", desc: "For completing a difficult challenge on 7 Cups to help build the community", n: 130},
{id: "l367", name: "Meet & Greet", desc: "For welcoming new members and listeners in the intro forums", n: 7296},
{id: "l499", name: "musicalMagic", desc: "For spreading kindness in the listener rooms.", n: 6},
{id: "l363", name: "NAMI Messenger", desc: "For people to share how they told someone at 7 Cups about the NAMI community and/or NAMI resources", n: 148},
{id: "l356", name: "NAMI Oath", desc: "For taking the NAMI Community Oath and dedicating yourself to the NAMI community on 7 Cups", n: 782},
{id: "l476", name: "Needs Reply Team", desc: "For forum team members focused on "Needs Reply" queue", n: 22},
{id: "l461", name: "New Mom Support Group", desc: "For members of the new Mom Support Group", n: 0},
{id: "l312", name: "Olympic Rings", desc: "For participating in an Olympic Challenge", n: 1},
{id: "l342", name: "Online Therapy", desc: "For Therapists that provide online therapy on 7 Cups", n: 356},
{id: "l185", name: "Oprah", desc: "For leading 12+ chat room discussions", n: 187},
{id: "l153", name: "Orator", desc: "For making 1,000+ forum posts", n: 168},
{id: "l400", name: "Parenting & Pregnancy", desc: "For dedication to supporting those in the Parenting & Pregnancy Community", n: 3},
{id: "l235", name: "People of Color Support", desc: "For supporting Young People of Color in the 7 Cups community", n: 147},
{id: "l200", name: "Perinatal Support", desc: "For special dedication to supporting those in need of perinatal support", n: 7},
{id: "l276", name: "Pop-Up Ninja", desc: "For leading 3+ pop-up discussions in 1 week. Like a ninja.", n: 19},
{id: "l399", name: "Positivity Support", desc: "For dedication to supporting those in the Motivation & Self-Help Community", n: 11},
{id: "l331", name: "Power Welcomer", desc: "For Listeners who are part of the member welcome team", n: 206},
{id: "l440", name: "Purposeful Parent", desc: "For participating in a parenting-related event", n: 0},
{id: "l199", name: "Quality Guide", desc: "For writing a topic guide to help educate the community", n: 10},
{id: "l154", name: "Ray of Hope", desc: "For sending 1,000+ messages in a Group Support Chatroom", n: 3262},
{id: "l340", name: "Ready for Change", desc: "For Change group workshop participants", n: 0},
{id: "l223", name: "Relationship Support", desc: "For dedication to supporting those in the 7 Cups Relationship Community", n: 31},
{id: "l430", name: "Resolution Ruler", desc: "For participating in a resolution event", n: 12},
{id: "l405", name: "Safety Patrol", desc: "A member of the flagging profiles team!", n: 779},
{id: "l423", name: "Safety Support", desc: "For dedication to supporting the Safety & Knowledge Community", n: 14},
{id: "l429", name: "Santa's Helper", desc: "For participating in a holiday event", n: 87},
{id: "l474", name: "Santapaws 2019", desc: "For coming in first in one of the Santapaws 2019 competition categories!", n: 0},
{id: "l435", name: "SC Cupsiversary", desc: "For participating in a Subcommunity anniversary event", n: 0},
{id: "l226", name: "Schizophrenia Support", desc: "For special dedication to supporting those in need of schizophrenia support", n: 12},
{id: "l231", name: "Scrum Report", desc: "For continually tracking volunteer work to show your progress to the community", n: 141},
{id: "l271", name: "Secret Listener Messenger", desc: "For people who send gifts between secret buddies", n: 49},
{id: "l390", name: "Self-Harm Support Team", desc: "For dedication to supporting those in Self-Harm Recovery Community", n: 17},
{id: "l481", name: "Sharing Circle", desc: "For leading sharing circles", n: 29},
{id: "l155", name: "Shining Light", desc: "For sending 5,000+ messages in a Group Support Chatroom", n: 1141},
{id: "l146", name: "Small Chat", desc: "For sending 1,000+ messages in a listener chatroom", n: 2881},
{id: "l309", name: "Sparkler", desc: "For sending 500+ messages in a Group Support Chatroom", n: 5054},
{id: "l152", name: "Speaker", desc: "For making 500+ forum posts", n: 333},
{id: "l402", name: "Spring Events", desc: "For those who participated in a Spring event.", n: 61},
{id: "l191", name: "Startup Support Pro", desc: "For providing excellent support to the startup community", n: 10},
{id: "l269", name: "Stigma Warrior", desc: "For actively spreading awareness against stigmas as part of the 7 cups community", n: 2},
{id: "l307", name: "Strangers Unite", desc: "For sharing the “Talk to Strangers’ page with your personal network", n: 228},
{id: "l480", name: "Subcommunity Rockstar", desc: "For showing dedication, consistency and excellence as a sub-community team member", n: 14},
{id: "l403", name: "Summer Events", desc: "For those who participated in a Summer event.", n: 622},
{id: "l355", name: "Summer Events 2017", desc: "For participating in a special event organized by your subcommunity during the summer of 2017", n: 55},
{id: "l468", name: "Support Key", desc: "For access to LGBTQ+ and Disability group support rooms", n: 185},
{id: "l150", name: "Talker", desc: "For making 100+ forum posts", n: 1466},
{id: "l270", name: "Teen Chat Support", desc: "For Teen Stars who have chosen to be available ongoing chat support", n: 19},
{id: "l145", name: "Tiny Chat", desc: "For sending 500+ messages in a listener chatroom", n: 4416},
{id: "l391", name: "Trauma Support Team", desc: "For dedication to supporting those in Trauma Support Community", n: 10},
{id: "l288", name: "TS Key", desc: "For access to the Thinking Space room", n: 962},
{id: "l298", name: "Twinning", desc: "For having a listener twin & sticking by their side on 7 Cups", n: 428},
{id: "l149", name: "Voice", desc: "For making 50+ forum posts", n: 2520},
{id: "l204", name: "Weekly Challenge 1st", desc: "For winning first place in a weekly challenge", n: 57},
{id: "l205", name: "Weekly Challenge 2nd", desc: "For earning 2nd place during a weekly challenge", n: 58},
{id: "l206", name: "Weekly Challenge 3rd", desc: "For earning 3rd place during a weekly challenge", n: 41},
{id: "l291", name: "Welcome & Support", desc: "For welcoming new subscribers in a sub-community", n: 7},
{id: "l341", name: "Welcoming Superstar", desc: "For listeners who welcome 24 new listeners every week", n: 12},
{id: "l398", name: "Wiki Team", desc: "For anyone who signs helps support the 7 Cups wiki", n: 66},
{id: "l392", name: "Winter 2018 Special Events", desc: "For community members that participated in a winter 2018 event", n: 177},
{id: "l472", name: "Winter Events", desc: "For those who participated in a Winter event", n: 47},
{id: "l320", name: "WMH Day", desc: "For assisting with World Mental Health Day events", n: 19},
{id: "l477", name: "World Connections", desc: "For dedication to supporting those in the 7 Cups Around the World", n: 2},
{id: "l211", name: "Bat Signal", desc: "For listeners who respond to the bat call and help the community by taking a general chat!", n: 772},
{id: "l44", name: "Active Minds", desc: "For reaching out to colleges and universities", n: 47},
{id: "l260", name: "Cup Connect", desc: "For spreading the word about 7 Cups to help make the world a better place", n: 254},
{id: "l384", name: "Diary Study", desc: "For those who participate in the teen diary study", n: 13},
{id: "l193", name: "Feedback", desc: "For receiving feedback in chats or group support and openly learning from it", n: 1192},
{id: "l46", name: "First Step", desc: "For reaching out to the Alcoholics Anonymous population and helping those who have struggled with alcoholism to feel supported on 7 Cups of Tea", n: 27},
{id: "l379", name: "Five Steps", desc: "For completing 5 steps on your listener progress path", n: 241452},
{id: "l381", name: "Hang 10", desc: "For completing 10 steps on your listener progress path", n: 150328},
{id: "l202", name: "Highness of Hearts", desc: "For being voted one of the most dedicated and supportive and appreciative people during the 2015 Appreciation Festival", n: 32},
{id: "l263", name: "Milestone Team", desc: "For members and listeners who have opted to provide support to those sharing milestones (Show the Way And Triumph)", n: 59},
{id: "l278", name: "Quality Beam", desc: "For actively looking to improve mentoring skills during Quality Week.", n: 13},
{id: "l45", name: "Ramp Up", desc: "For helping an organization become a 7 Cups of Tea partner", n: 3},
{id: "l47", name: "Stepping Up", desc: "For reaching out to the Narcotics Anonymous population and helping those who have struggled with drug addiction to feel supported on 7 Cups of Tea", n: 23},
{id: "l325", name: "Tick Tock", desc: "For reaching reaching ten 1-on-1 chats", n: 193067},
{id: "l413", name: "Translation Master", desc: "For translating 500+ terms to help bring 7 Cups to all people", n: 24},
{id: "l412", name: "Translation Microscope", desc: "For helping to proofread and edit translated terms within the Translation Project", n: 1},
{id: "l485", name: "Translation Pro", desc: "For translating 1000+ terms to help bring 7 Cups to all people", n: 5},
{id: "l52", name: "Translator", desc: "For taking the lead to bring 7 cups of tea to another country and translating the site into the native language", n: 420},
{id: "l299", name: "3rd Birthday Party", desc: "For sharing your referral link in honor of 7 Cups’ 3rd Birthday", n: 134},
{id: "l106", name: "Da Vinci", desc: "For creating content for 7 Cups of Tea & its social media channels", n: 74},
{id: "l54", name: "Envoy", desc: "For having a personal referral URL visited by 300 unique people", n: 160},
{id: "l160", name: "Help Angel", desc: "For recruiting a new Member to 7 Cups of Tea", n: 3668},
{id: "l55", name: "Herald", desc: "For having a personal referral URL visited by 1,000 unique people", n: 50},
{id: "l319", name: "MedX", desc: "For feeling proud and spreading the news that 7 Cups won the Stanford MedX Prize for Health Care Systems Design!", n: 182},
{id: "l53", name: "Messenger", desc: "For having a personal referral URL visited by 50 unique people", n: 1657},
{id: "l194", name: "PH Upvote", desc: "For supporting the community by upvoting us on Product Hunt", n: 137},
{id: "l26", name: "Recruit", desc: "For recruiting a new Listener to 7 Cups of Tea", n: 1967},
{id: "l366", name: "Social Butterfly", desc: "For being a committed soldier spreading the word about 7cups for 3 consecutive months!", n: 18},
{id: "l365", name: "Social Soldier", desc: "For uniforming up and dedicating time to reach out to people in need of support for 1 month!", n: 52},
{id: "l503", name: "Super Supporter", desc: "For following 7 Cups on a social media platform", n: 164},
{id: "l15", name: "Dewey", desc: "For making suggestions that help 7 Cups of Tea become more organized", n: 34},
{id: "l27", name: "Edison", desc: "For finding creative ways to help more people through 7 Cups of Tea", n: 34},
{id: "l14", name: "Editor", desc: "For helping to edit content on the site", n: 25},
{id: "l16", name: "Educator", desc: "For creative educational materials in partnership with 7 Cups of Tea", n: 12},
{id: "l29", name: "Icon", desc: "For helping to create new badges and awards for 7 Cups of Tea’s listeners", n: 30},
{id: "l13", name: "Senator", desc: "For being a valued member of community with ability to vote on future site directions", n: 6},
{id: "l230", name: "7Cups Feed", desc: "For curators of the @7Cups feed", n: 18},
{id: "l244", name: "Aficionado", desc: "For being an active member of the feed team", n: 121},
{id: "l492", name: "AL1 Team", desc: "For Active Listening 1 graders", n: 1},
{id: "l493", name: "AL2 Team", desc: "For Active Listening 2 graders", n: 6},
{id: "l494", name: "AL3 Team", desc: "For Active Listening 3 graders", n: 5},
{id: "l495", name: "AL4 Team", desc: "For Active Listening 4 graders", n: 5},
{id: "l70", name: "Ambassador", desc: "For early commitment to the 7 Cups of Tea mission and for going above and beyond in service to the community.", n: 19},
{id: "l358", name: "Bandit", desc: "For supporting the community with consistency", n: 29},
{id: "l397", name: "Bandit 2", desc: "For reliable community support", n: 26},
{id: "l339", name: "Campus Leader", desc: "For establishing 7 Cups community on campus", n: 30},
{id: "l189", name: "Campus Stringer", desc: "For spreading awareness through campus publications", n: 13},
{id: "l327", name: "Chapter Leader", desc: "For serving as a 7 Cups chapter leader", n: 8},
{id: "l326", name: "Chapter Member", desc: "For being a member of a 7 Cups chapter", n: 7},
{id: "l328", name: "Chapter President", desc: "For serving as the President of a 7 Cups chapter", n: 3},
{id: "l330", name: "Chapter Secretary", desc: "For serving as the Secretary of a 7 Cups chapter", n: 2},
{id: "l329", name: "Chapter VP", desc: "For serving as the Vice President of a 7 Cups chapter", n: 2},
{id: "l248", name: "Chat Support", desc: "For Mentors who have chosen to be available ongoing chat support", n: 35},
{id: "l107", name: "Chatroom Mentor", desc: "For monitoring the Listener chatroom & answering questions", n: 28},
{id: "l115", name: "Chatroom Mentor Leader", desc: "For leading chatroom dialogue & managing morale", n: 14},
{id: "l346", name: "CL Intern Leader", desc: "For maintaining and managing the campus leader internship program.", n: 1},
{id: "l110", name: "Community Mentor", desc: "For spreading the word & creating content for social media", n: 25},
{id: "l118", name: "Community Mentor Leader", desc: "For managing lead sharing campaigns & encouraging sharing", n: 43},
{id: "l311", name: "Country Champion", desc: "For spreading the word about 7 Cups in your country & being a leader for your country community on and off of 7 Cups", n: 13},
{id: "l310", name: "Country Leader", desc: "For on-site community builders, helping to build country communities at 7 Cups", n: 7},
{id: "l182", name: "Depression Support", desc: "For dedication to supporting those in the 7 Cups Depression Community", n: 53},
{id: "l351", name: "Doorkeeper", desc: "For opening and closing chatrooms for discussions and events", n: 134},
{id: "l456", name: "Editorial Assistant", desc: "For being a member of the content volunteer team", n: 54},
{id: "l475", name: "Enthusiast 2.0", desc: "For developing the community identity with enthusiasm", n: 12},
{id: "l134", name: "Featured Leader", desc: "For exceptional dedication to the 7 Cups of Tea mission", n: 99},
{id: "l304", name: "Feed Mod", desc: "For community members who moderate the feed", n: 5},
{id: "l396", name: "Forum Admin", desc: "For forum Leaders who manage the forum moderation queue", n: 7},
{id: "l388", name: "Forum Flag Team", desc: "For members of the forum flag team", n: 19},
{id: "l318", name: "Forum Key", desc: "For project leaders who support their project via forum engagement", n: 40},
{id: "l108", name: "Forum Mentor", desc: "For monitoring the Forum & keeping it active", n: 17},
{id: "l116", name: "Forum Mentor Leader", desc: "For guiding & encouraging forum activity", n: 7},
{id: "l404", name: "General Support Team", desc: "For dedication to supporting those in the General Support Community", n: 6},
{id: "l234", name: "Group Mentor Leader", desc: "For monitoring group support quality", n: 3},
{id: "l364", name: "Group Mod Key", desc: "For 7 Cups Partners who host group discussions for their communities", n: 4},
{id: "l181", name: "Group Mod Leader", desc: "For supervising and supporting Group Mods", n: 4},
{id: "l261", name: "Guide Team", desc: "For being a member of the Listener Written Guide Approval Team", n: 12},
{id: "l267", name: "Healthy Living Team", desc: "For leading the Healthy Living support team", n: 12},
{id: "l323", name: "Intern Mentor", desc: "For monitoring and supporting the internship program", n: 25},
{id: "l498", name: "Leadership Graduate", desc: "For listeners who have successfully completed the Leadership Development Program", n: 34},
{id: "l497", name: "Leadership Trainee", desc: "For listeners currently enrolled in Leadership Development Program", n: 236},
{id: "l465", name: "Listener Coach", desc: "For mentors who support listeners through the Listener Coaching Program", n: 34},
{id: "l209", name: "Listener Verifier Team", desc: "For experienced members of the listener community who support listeners through the verified listener process", n: 149},
{id: "l457", name: "Marketing Assistant", desc: "For being a member of the marketing volunteer team", n: 9},
{id: "l250", name: "Mindfulness Support", desc: "For leading regular Mindfulness sessions", n: 32},
{id: "l454", name: "Mod 2.0", desc: "For mod program initiatives", n: 40},
{id: "l350", name: "Mod Champion", desc: "For fulfilling 200 group chats in 4 months as a Group Mod", n: 187},
{id: "l349", name: "Mod Major", desc: "For fulfilling 150 group chats in 3 months as a Group Mod", n: 205},
{id: "l348", name: "Mod On", desc: "For fulfilling 100 group chats in 2 months as a Group Mod", n: 237},
{id: "l347", name: "Mod Star", desc: "For fulfilling 50 group chats in 1 month as a Group Mod", n: 264},
{id: "l273", name: "Operations Assistant", desc: "For assisting in site operations", n: 12},
{id: "l274", name: "Operations Mentor", desc: "For leading teams working on site operations", n: 8},
{id: "l28", name: "PB", desc: "For being a huge believer in the vision of 7 Cups of Tea, awarded by the founder, the first PB award will be awarded July 2014", n: 12},
{id: "l256", name: "Project Agent", desc: "For helping to manage a project in the community", n: 52},
{id: "l416", name: "Q & A Editing Crew", desc: "For members of the Q & A team that can edit Q & A replies", n: 3},
{id: "l383", name: "Q & A Glitter Trotter", desc: "For members of the Q & A approval team", n: 36},
{id: "l460", name: "Quality Maven", desc: "For verifying 75 listeners through the Verified Listener process", n: 7},
{id: "l109", name: "Quality Mentor", desc: "For monitoring Listener quality", n: 44},
{id: "l117", name: "Quality Mentor Leader", desc: "For managing listener quality as a high level listener", n: 17},
{id: "l386", name: "Question Crew", desc: "For members of the Q & A team that help with question approvals", n: 3},
{id: "l359", name: "Rocket", desc: "For supporting the community with enthusiasm", n: 35},
{id: "l395", name: "SC Forum Mentor", desc: "For forum mentors who focuse exclusively in their Subcommunity", n: 1},
{id: "l467", name: "Smalls", desc: "For a can-do attitude, personal sacrifice and service to the community", n: 3},
{id: "l213", name: "Special Events Organizer", desc: "For organizing community building events", n: 35},
{id: "l251", name: "Student Support", desc: "For dedication to supporting those in the 7 Cups High School Support Community", n: 38},
{id: "l305", name: "Support Plus", desc: "For leading special support sessions on specific topics", n: 63},
{id: "l212", name: "Support Room Mentor", desc: "For leading a group support team", n: 10},
{id: "l266", name: "Support Team Teen Star", desc: "For helping to lead a support team", n: 5},
{id: "l119", name: "Teen Chatroom Leader", desc: "For leading teen chatroom dialogue & managing morale", n: 5},
{id: "l111", name: "Teen Chatroom Mentor", desc: "For monitoring the Teen Listener chatroom & answering questions", n: 13},
{id: "l105", name: "Teen Chatroom Star", desc: "For teen listeners who help moderate the 7 Cups listener chatrooms", n: 4},
{id: "l262", name: "Teen CM", desc: "For the Teen Community Manager of the Day", n: 0},
{id: "l228", name: "Teen Community Star", desc: "For teen listeners who help spread the word and create content for social media", n: 13},
{id: "l201", name: "Teen Forum Star", desc: "For teen listeners who help moderate the 7 Cups forums", n: 0},
{id: "l464", name: "Teen Listener Coach", desc: "For mentors who support listeners through the Teen Listener Coaching Program", n: 10},
{id: "l120", name: "Teen Quality Leader", desc: "For managing teen listener quality as a high level listener", n: 5},
{id: "l112", name: "Teen Quality Mentor", desc: "For monitoring Teen Listener quality", n: 19},
{id: "l229", name: "Teen Quality Star", desc: "For teen listeners who help monitor teen listeners quality", n: 9},
{id: "l257", name: "Teen Star Leader", desc: "For helping new teen stars adjust and going above and beyond in service to the community", n: 3},
{id: "l245", name: "Teen Transitioning Mentor", desc: "For supporting teens previous,during and after they move to the adult side", n: 19},
{id: "l322", name: "Training Badge", desc: "For access to special leadership training rooms", n: 107},
{id: "l265", name: "Transition Mentor Leader", desc: "For supporting teens through their transition to the adult side as a high level listener", n: 0},
{id: "l458", name: "Writer", desc: "For being a writer on the content volunteer team", n: 64},
{id: "l281", name: "12 Steps", desc: "For completion of the 12 Step Working Guide", n: 8654},
{id: "l289", name: "7 Cups Intern", desc: "For listeners who are currently active in the 7 Cups internship program", n: 470},
{id: "l290", name: "7 Cups Intern Grad", desc: "For listeners who successfully completed the 7 Cups internship program", n: 642},
{id: "l275", name: "7Cups Guide", desc: "For completion of the 7 Cups for the Searching Soul eBook", n: 9858},
{id: "l171", name: "ACT Therapy", desc: "For completion of the ACT Therapy Course", n: 15296},
{id: "l236", name: "ADHD", desc: "For completion of the Attention-Deficit/Hyperactivity Disorder Course", n: 10850},
{id: "l102", name: "Alcohol & Drug Abuse", desc: "For completion of the Alcohol & Drug Course", n: 18402},
{id: "l77", name: "Anxiety", desc: "For completion of the Anxiety Course", n: 30622},
{id: "l490", name: "Becoming a Leader", desc: "For completing Course 2 of the Leadership Development Program", n: 54},
{id: "l239", name: "Boundaries", desc: "For completion of the Boundaries Course", n: 9001},
{id: "l122", name: "Bullying", desc: "For completion of the Bullying Course", n: 17269},
{id: "l123", name: "Chronic Pain", desc: "For completion of the Chronic Pain Course", n: 11486},
{id: "l344", name: "CL Intern", desc: "For participating in the campus leader internship program.", n: 0},
{id: "l345", name: "CL Intern Grad", desc: "For graduating from the campus leader internship program.", n: 0},
{id: "l167", name: "College Guide", desc: "For completion of the College Guide Course", n: 13943},
{id: "l282", name: "Community 101", desc: "For learning about the 7 Cups community best practices & skills", n: 11247},
{id: "l84", name: "Crisis Intervention", desc: "For completion of the Crisis Intervention Course", n: 13658},
{id: "l104", name: "Cultural Diversity", desc: "For completion of the Cultural Diversity Course", n: 13879},
{id: "l78", name: "Depression", desc: "For completion of the Depression Course", n: 30924},
{id: "l394", name: "Diabetes CBT", desc: "For completion of the Diabetes CBT Guide", n: 2922},
{id: "l79", name: "Eating Disorders", desc: "For completion of the Eating Disorders Course", n: 15543},
{id: "l170", name: "Exercise Motivation", desc: "For completion of the Exercise Motivation Course", n: 10383},
{id: "l125", name: "Family Stress", desc: "For completion of the Family Stress Course", n: 14226},
{id: "l103", name: "Family Support", desc: "For completion of the Parenting Course", n: 10023},
{id: "l240", name: "Forgiveness", desc: "For completion of the Forgiveness Course", n: 7390},
{id: "l247", name: "Getting Unstuck", desc: "For completion of the Getting Unstuck Course", n: 6976},
{id: "l127", name: "Graduate", desc: "For successful completion of the the Active Listening 1 Course", n: 12958},
{id: "l509", name: "Grasshopper", desc: "For Listeners who complete the New Listener Support Training when they join 7 Cups", n: 4},
{id: "l241", name: "Grief", desc: "For completion of the Grief Course", n: 7218},
{id: "l426", name: "Hope Training", desc: "For completion of the Hope Training Guide", n: 2630},
{id: "l332", name: "Intern Buddy", desc: "For intern graduates who are guiding new interns", n: 3},
{id: "l491", name: "Leadership Principles", desc: "For completing Course 4 of the Leadership Development Program", n: 36},
{id: "l168", name: "Loneliness Guide", desc: "For completion of the Loneliness Guide Course", n: 14095},
{id: "l242", name: "Managing Bipolar", desc: "For completion of the Managing Bipolar Course", n: 8978},
{id: "l80", name: "Managing Emotions", desc: "For completion of the Managing Emotions Course", n: 16997},
{id: "l243", name: "Managing Finances", desc: "For completion of the Managing Finances Course", n: 6131},
{id: "l128", name: "Master", desc: "For successful completion of the Active Listening 2 Course", n: 4187},
{id: "l343", name: "NAMI Listener", desc: "For listeners who have successfully completed the NAMI listener training guide", n: 4463},
{id: "l466", name: "New Mom Support", desc: "For Listeners who have completed New Moms training", n: 1412},
{id: "l238", name: "OCD", desc: "For completion of the Obsessive-Compulsive Disorder Course", n: 6063},
{id: "l81", name: "Panic Attacks", desc: "For completion of the Panic Attacks Course", n: 14422},
{id: "l441", name: "Peer Pro", desc: "For completing all 12 of the Peer Trainings", n: 1454},
{id: "l442", name: "Peer Training 01", desc: "For completing Session 01 of Peer Training", n: 2795},
{id: "l443", name: "Peer Training 02", desc: "For completing Session 02 of Peer Training", n: 2166},
{id: "l444", name: "Peer Training 03", desc: "For completing Session 03 of Peer Training", n: 1946},
{id: "l445", name: "Peer Training 04", desc: "For completing Session 04 of Peer Training", n: 1783},
{id: "l446", name: "Peer Training 05", desc: "For completing Session 05 of Peer Training", n: 1718},
{id: "l447", name: "Peer Training 06", desc: "For completing Session 06 of Peer Training", n: 1670},
{id: "l448", name: "Peer Training 07", desc: "For completing Session 07 of Peer Training", n: 1568},
{id: "l449", name: "Peer Training 08", desc: "For completing Session 08 of Peer Training", n: 1540},
{id: "l450", name: "Peer Training 09", desc: "For completing Session 09 of Peer Training", n: 1511},
{id: "l451", name: "Peer Training 10", desc: "For completing Session 10 of Peer Training", n: 1499},
{id: "l452", name: "Peer Training 11", desc: "For completing Session 11 of Peer Training", n: 1475},
{id: "l453", name: "Peer Training 12", desc: "For completing Session 12 of Peer Training", n: 1482},
{id: "l233", name: "People of Color Guide", desc: "For completion of the Young People of Color Course", n: 5897},
{id: "l198", name: "Perinatal", desc: "For completion of the Perinatal Mood Disorder Course", n: 6252},
{id: "l488", name: "Personal Leadership 101", desc: "For completing Course 1 of the Leadership Development Program", n: 83},
{id: "l489", name: "Personal Leadership 102", desc: "For completing Course 3 of the Leadership Development Program", n: 37},
{id: "l486", name: "Pineapple", desc: "For completing the Pineapple Support guide.", n: 834},
{id: "l124", name: "Psychological First Aid", desc: "For completion of the Psychological First Aid (PFA) Course", n: 10271},
{id: "l277", name: "Rocket Listener", desc: "For successful completion of Active Listening 4 Course", n: 1206},
{id: "l210", name: "Schizophrenia", desc: "For completion of the Coping with Schizophrenia Course", n: 8300},
{id: "l129", name: "Scholar", desc: "For successful completion of the Active Listening 3 Course", n: 1711},
{id: "l100", name: "Self Harm", desc: "For completion of the Self Harm Course", n: 18788},
{id: "l101", name: "Sexual Abuse", desc: "For completion of the Sexual Abuse Course", n: 14515},
{id: "l126", name: "Sleeping Well", desc: "For completion of the Sleeping Well Course", n: 12773},
{id: "l237", name: "Social Anxiety", desc: "For completion of the Social Anxiety Course", n: 8280},
{id: "l190", name: "Startup Support", desc: "For completion of the Startup Support Course", n: 7029},
{id: "l82", name: "Surviving Breakups", desc: "For completion of the Surviving Breakups Course", n: 23309},
{id: "l246", name: "Surviving Domestic Assault", desc: "For completion of the Surviving Domestic Assault Course", n: 5538},
{id: "l169", name: "Test Anxiety", desc: "For completion of the Test Anxiety Course", n: 10776},
{id: "l83", name: "Traumatic Experiences", desc: "For completion of the Traumatic Experiences Course", n: 11411},
{id: "l393", name: "Weight Management", desc: "For completion of the Weight Management Guide", n: 2789},
{id: "l99", name: "Work Related Stress", desc: "For completion of the Work Related Stress Course", n: 10135},
{id: "l253", name: "Above & Beyond", desc: "For connecting to a Mentor and learning something new about listening", n: 684},
{id: "l165", name: "Break-A-Leg", desc: "For overcoming, stress, anxiety & fear to try something new", n: 2305},
{id: "l316", name: "Champion Self-Esteem", desc: "For completing 30 days of a Self Esteem Challenge", n: 25},
{id: "l314", name: "Entrepreneur Self-Esteem", desc: "For completing 10 days of a self-esteem Challenge", n: 59},
{id: "l437", name: "Kindness Challenge", desc: "For completing a Kindness Challenge", n: 196},
{id: "l163", name: "Lean-On-Me", desc: "For helping a fellow listener after a difficult chat, nominated by 5 Listeners", n: 89},
{id: "l315", name: "Master Self-Esteem", desc: "For completing 20 days of a self-esteem Challenge", n: 58},
{id: "l321", name: "Pink Ribbon", desc: "For participating in a Breast Cancer Awareness activity", n: 67},
{id: "l255", name: "Positivity Challenge", desc: "For participating in the 7 day positivity challenge", n: 195},
{id: "l164", name: "Relationships", desc: "For building supportive relationships with fellow listeners, nominated by 5 other listeners", n: 182},
{id: "l161", name: "Self-Care", desc: "For participating in a self-care practice 3 times a week for 1 month", n: 2402},
{id: "l166", name: "Self-Love", desc: "For doing something nice for yourself everyday for a month", n: 1670},
{id: "l254", name: "Soaring", desc: "For continuing Listener community education by passing on what you’ve learned from your feedback/Menteeship to others", n: 292},
{id: "l502", name: "Soul Searcher", desc: "For reading and reviewing the 7 Cups for the Searching Soul book", n: 101},
{id: "l162", name: "Trust Fall", desc: "For seeking peer support after hard chat, nominated by 2 Peer Support Listeners", n: 185}]