cheat = {
1: 'Do welcome members on behalf of 7 Cups and tell them your preferred name.',
2: 'Do reflect the member\'s feelings exactly.',
3: 'Do reflect implied feelings accurately.',
4: 'Do ask questions about the member\'s feelings.',
5: 'Do react authentically to what the member tells you.',
6: 'Do reflect factual content exactly if there are no feelings to talk about.',
7: 'Do encourage the member to say more.',
8: 'Do summarize.',
9: 'Do use conversation fillers.',
10: 'Do ask open questions to encourage the member to say more.',
11: 'Do ask closed questions when the conversation is stuck.',
12: 'Do disclose facts about yourself when it seems natural.',
13: 'Do refer to another listener when you need to.',

21: 'Don\'t continue the chat if the member is taking action to end their life (actively suicidal).',
22: 'Don\'t share contact information or use contact information a member shares with you.',
23: 'Don\'t click on links unless you are certain they go to well-known safe websites.',
24: 'Don\'t tell the member what they must feel or should feel (emotional abuse).',
25: 'Don\'t talk about your own feelings or imaginary feelings (I-statements).',
26: 'Don\'t give advice.',
27: 'Don\'t make suggestions.',
28: 'Don\'t make assumptions.',
29: 'Don\'t try to solve the member\'s problems.',
30: 'Don\'t play at counselling or psychotherapy.',
31: 'Don\'t change the subject.',
32: 'Don\'t make comments.',
33: 'Don\'t judge.',
34: 'Don\'t use unprofessional language.',
35: 'Don\'t encourage denial.',
36: 'Don\'t encourage distraction.'
}
