cheat = [
'Do welcome members on behalf of 7 Cups and tell them your preferred name.',
'Do reflect the member\'s feelings exactly.',
'Do reflect implied feelings accurately.',
'Do ask questions about the member\'s feelings.',
'Do react authentically to what the member tells you.',
'Do reflect factual content exactly if there are no feelings to talk about.',
'Do encourage the member to say more.',
'Do summarize.',
'Do use conversation fillers.',
'Do ask open questions to encourage the member to say more.',
'Do ask closed questions when the conversation is stuck.',
'Do disclose facts about yourself when it seems natural.',
'Do refer to another listener when you need to.',
'',
'',
'',
'',
'',
'',
'',
'',
'Don\'t continue the chat if the member is taking action to end their life (actively suicidal).',
'Don\'t share contact information or use contact information a member shares with you.',
'Don\'t click on links unless you are certain they go to well-known safe websites.',
'Don\'t tell the member what they must feel or should feel (emotional abuse).',
'Don\'t talk about your own feelings or imaginary feelings (I-statements).',
'Don\'t give advice (not even suggestions).',
'Don\'t play at counselling or psychotherapy, or try to solve the member\'s problems.',
'Don\'t change the subject.',
'Don\'t make comments or assumptions.',
'Don\'t judge.',
'Don\'t use unprofessional language.',
'Don\'t encourage denial or distraction.',
]