data = [{"url":"/home/welcome/","title":"Newbie Hub","strap":"This is a space for newbies to learn, ask and get involved in the community.","forums":[{"url":"/forum/NewbieHub_27/SubCommunitiesPostsTazziesSpace_1940/","title":"Sub-Communities Posts| Tazzie's Space","strap":" Sub-Communities' Ice breakers, Q and A's and Forum Discussion Threads For Newbies To Join In!"},
{"url":"/forum/NewbieHub_27/7CupsofTeaMissionCoreValues_207/","title":"7 Cups of Tea Mission & Core Values ","strap":"Information about 7 Cups of Tea"},
{"url":"/forum/NewbieHub_27/WelcomeIntroductionsto7CupsGeneralConversations_1163/","title":"Welcome & Introductions to 7 Cups! | General Conversations!","strap":"you've joined 7 Cups! We can't wait to get to know you"},
{"url":"/forum/NewbieHub_27/Informationaboutusing7Cups_792/","title":"Information about using 7 Cups","strap":"Please use these threads to get more acquainted with 7 Cups"},
{"url":"/forum/NewbieHub_27/7CupsPodcast_1073/","title":"7 Cups Podcast","strap":"Check out old episodes of the 7 Cups Podcast here! :)"},
{"url":"/forum/NewbieHub_27/CommunityGuidelinesandProtocol_446/","title":"Community Guidelines and Protocol","strap":"Please keep the following guidelines in mind as you contribute to the 7 Cups of Tea Forum."},
{"url":"/forum/NewbieHub_27/HopeNewsletter_923/","title":"Hope Newsletter","strap":"Our community's newsletter"},
{"url":"/forum/NewbieHub_27/Resourcesat7CupstoHelpYou_1275/","title":"Resources at 7 Cups to Help You","strap":"Here are some of the major resources that members and listeners have available to them at 7cups to help them on their journey"},
{"url":"/forum/NewbieHub_27/SubCommunitiesat7Cups_1924/","title":"Sub-Communities at 7 Cups","strap":"Information on various communities across the site,"},
{"url":"/forum/NewbieHub_27/OurVisionforaBetterWorld_334/","title":"Our Vision for a Better World","strap":"Our mission, goals, and how we can work together to make the world a better place."},
{"url":"/forum/NewbieHub_27/WelcomeParties_1633/","title":"Welcome Parties!!","strap":"Come celebrate and honor all the new members at monthly welcome parties"},
{"url":"/forum/NewbieHub_27/JoinDateAnimalClubs_1916/","title":"Join Date Animal Clubs","strap":"Meet users who joined the same month as you!"},
{"url":"/forum/NewbieHub_27/Explore7Cups_1887/","title":"Explore 7 Cups","strap":"Learn about all 7 Cups has to offer here!"}]},
{"url":"/home/generalsupport/","title":"General Support","strap":"Here you can seek support on a variety of topics such as: getting unstuck, long term support & boundaries, managing emotions, mental health & awareness, physical health & awareness, self care support, and stigma support.","forums":[{"url":"/forum/GeneralSupport_28/DiaryEntriesConnections_1597/","title":"Diary Entries & Connections","strap":"If you only want certain people commenting (or only yourself), post here and let us know of your restrictions"},
{"url":"/forum/GeneralSupport_28/ManagingEmotions_1601/","title":"Managing Emotions","strap":"Post about managing your emotions here :)"},
{"url":"/forum/GeneralSupport_28/ResourcesforGeneralSupport_931/","title":"Resources for General Support","strap":"Read and Share Resources about Mental Health or other topics"},
{"url":"/forum/GeneralSupport_28/IntroductionsIcebreakersCheckins_1555/","title":"Introductions, Icebreakers, & Check-ins!","strap":"Welcome to the General Support Community! Let us get to know you :)"},
{"url":"/forum/GeneralSupport_28/MembersClassifieds_360/","title":"Members Classifieds","strap":"Where 7 Cups members post what kind of chat support/ listener they are looking for"},
{"url":"/forum/GeneralSupport_28/LongTermSupportBoundaries_1613/","title":"Long Term Support & Boundaries","strap":"Learn about long term support offered at 7 Cups here!"},
{"url":"/forum/GeneralSupport_28/GeneralEntries_1596/","title":"General Entries","strap":"Feel free to share what you are going through here :)"},
{"url":"/forum/GeneralSupport_28/GettingUnstuck_1599/","title":"Getting Unstuck","strap":"If you are stuck or need help reframing a thought, let us know here :)"},
{"url":"/forum/GeneralSupport_28/SelfCareSupport_351/","title":"Self Care Support","strap":"Let us know how you are managing self care here :)"},
{"url":"/forum/GeneralSupport_28/Discussions_1598/","title":"Discussions","strap":"Group Support and Forum Discussions :)"},
{"url":"/forum/GeneralSupport_28/AMAAskMeAnything_127/","title":"AMA - Ask Me Anything","strap":"If you are open to questions about yourself from the community, you can host an AMA here :)"},
{"url":"/forum/GeneralSupport_28/ListenersClassifieds_361/","title":"Listeners Classifieds","strap":"A places for listeners to post about themselves and the types of members they'd like to support"},
{"url":"/forum/GeneralSupport_28/MentalHealthSupportAwareness_1600/","title":"Mental Health Support & Awareness","strap":"Post about your mental health, well-being, or illness here :)"},
{"url":"/forum/GeneralSupport_28/StigmaSupport_126/","title":"Stigma Support","strap":"Fight Stigma and seek support here :)"},
{"url":"/forum/GeneralSupport_28/GeneralSupportCommunityTeam_407/","title":"General Support Community Team","strap":"Learn More About the General Support Team Here :)"},
{"url":"/forum/GeneralSupport_28/PhysicalHealthSupportAwareness_1603/","title":"Physical Health Support & Awareness","strap":"Post about injury, illness, and other physical health topics here! "}]},
{"url":"/home/35plus/","title":"35 & Over Community","strap":"","forums":[]},
{"url":"/home/50plus/","title":"50 & Over Community","strap":"Welcome, friends, to the 50 & Over Community Online Community at 7 Cups of Tea.","forums":[{"url":"/forum/50OverCommunity_193/Checkin_1704/","title":"Check in ","strap":"Check in on the latest topics we are discussing and introduce yourself"},
{"url":"/forum/50OverCommunity_193/QuizzesFunandIcebreakers_560/","title":"Quizzes, Fun and Icebreakers","strap":"This is a section where you can share any games, quizzes, icebreakers, jokes or simply have fun and un-wind!"},
{"url":"/forum/50OverCommunity_193/WellnessinBodyandMind_1703/","title":"Wellness in Body and Mind","strap":"Staying Well, Goals, Exercise, Diet, Habits, Let's Share Ideas Here"},
{"url":"/forum/50OverCommunity_193/QAandDiscussions_1770/","title":"Q&A and Discussions","strap":"Here is a place to ask and answer questions and do forum discussions"},
{"url":"/forum/50OverCommunity_193/NewMembersWelcome_1717/","title":"New Members Welcome! ","strap":"Feel Free to Share a little or reply to posts"},
{"url":"/forum/50OverCommunity_193/EnjoyingLife_1706/","title":"Enjoying Life","strap":"Hobbies, what gives us joy, creativity, ideas, poetry, art, music"},
{"url":"/forum/50OverCommunity_193/CaringforOthersinOurLives_1876/","title":"Caring for Others in Our Lives","strap":"This is a place to post threads and posts on how caring for others is affecting us in positive and negative ways. PM soulsings if need help with post"},
{"url":"/forum/50OverCommunity_193/TeamToolsandTeamUpdates_1705/","title":"Team Tools and Team Updates","strap":"Find the latest tag list and team announcements"},
{"url":"/forum/50OverCommunity_193/50plusResourcesandArticles_1757/","title":"50plus Resources and Articles","strap":"This is a place to share articles you wrote or links to articles you find helpful. Resources at 7cups in the wiki or forums can also be linked to."},
{"url":"/forum/50OverCommunity_193/ChallengesWeFace_1702/","title":"Challenges We Face","strap":"Create threads or post on things that are challenging."},
{"url":"/forum/50OverCommunity_193/WomensTopicslikeMenopauseandPerimenopause_1853/","title":"Women's Topics like Menopause and Perimenopause","strap":"This is a place for women to post and reply to women who are going through some of the same challenges that you are. Come reply to a thread."}]},
{"url":"/home/interns/","title":"7 Cups Internship","strap":"","forums":[]},
{"url":"/forum/7CupsOnlineTherapyInformationDiscussion_157/","title":"7 Cups Online Therapy Information & Discussion","strap":"","forums":[]},
{"url":"/forum/ADDADHDSupport_68/","title":"ADD/ ADHD Support","strap":"","forums":[]},
{"url":"/home/addiction/","title":"Addiction Support","strap":"Our community is here to support you through any recovery, from alcohol and substances to gambling and internet, and more!  All are welcome to participate.","forums":[{"url":"/forum/AddictionSupport_131/SexandPornAddictionSupport_723/","title":"Sex and Porn Addiction Support","strap":"Here you can find support specific to sex or porn addiction. Press \"create a new thread\" to get a conversation started that is relevant to you!"},
{"url":"/forum/AddictionSupport_131/CheckinThreads_972/","title":"Checkin Threads","strap":"Let's check-in with one another here"},
{"url":"/forum/AddictionSupport_131/ForumDiscussions_1982/","title":"Forum Discussions","strap":"Topics for thought provoking conversations.  Discuss them here!"},
{"url":"/forum/AddictionSupport_131/InternetAddictionSupport_838/","title":"Internet Addiction Support","strap":"Support for those who have an addiction to the internet"},
{"url":"/forum/AddictionSupport_131/GeneralAddictionSupport_725/","title":"General Addiction Support","strap":"Not seeing what you need?  Seek support here for any addiction related issues."},
{"url":"/forum/AddictionSupport_131/FunwithGamesandIcebreakers_1869/","title":"Fun with Games and Icebreakers","strap":"Let's get to know each other with some fun activities! All are welcome to participate.  "},
{"url":"/forum/AddictionSupport_131/DrugAddictionSupport_720/","title":"Drug Addiction Support","strap":"Here you can find support specific to drug addiction. Press \"create a new thread\" to get a conversation started that is relevant to you!"},
{"url":"/forum/AddictionSupport_131/Events_1509/","title":"Events ","strap":"Events in the Subcommunity"},
{"url":"/forum/AddictionSupport_131/Lovedonesofpeoplewithaddictions_1825/","title":"Loved ones of people with addictions","strap":"A place for friends and family to get support"},
{"url":"/forum/AddictionSupport_131/AlcoholAddictionSupport_721/","title":"Alcohol Addiction Support","strap":"Here you can find support specific to alcohol addiction. Press \"create a new thread\" to get a conversation started that is relevant to you!"},
{"url":"/forum/AddictionSupport_131/AddictionQAsAMAs_726/","title":"Addiction Q&As / AMAs","strap":"Do you have a question about addiction? Create a thread and ask our community!"},
{"url":"/forum/AddictionSupport_131/WelcomeIntroduceYourselftotheCommunity_719/","title":"Welcome / Introduce Yourself to the Community","strap":"Get to know our Addiction Support Community here. Find connection & let us know who you are!"},
{"url":"/forum/AddictionSupport_131/GamblingAddictionSupport_722/","title":"Gambling Addiction Support","strap":"Here you can find support specific to gambling addiction. Press \"create a new thread\" to get a conversation started that is relevant to you!"},
{"url":"/forum/AddictionSupport_131/ResourcesforAddiction_724/","title":"Resources for Addiction","strap":"Share or seek resources to help manage your addictions"},
{"url":"/forum/AddictionSupport_131/AddictionSupportPrologues_1445/","title":"Addiction Support Prologues","strap":"A place where you can journal and write the chapters of your addiction story. Share your story here where we can join together and walk by one another"},
{"url":"/forum/AddictionSupport_131/AddictionSupportCommunityTeamAnnouncements_727/","title":"Addiction Support Community Team/ Announcements ","strap":"Learn More About the Addiction Support Community Team Here :)"}]},
{"url":"/home/anxiety/","title":"Anxiety Support","strap":"The 7 Cups Anxiety Support Community is here to ease the pain of living with anxiety.","forums":[{"url":"/forum/AnxietySupport_53/AnxietySupportShareYourStoryHowdoyoufeelrightnow_667/","title":"Anxiety Support - Share Your Story/How do you feel right now?","strap":"Let us know your experiences/how you're feeling and get some support!"},
{"url":"/forum/AnxietySupport_53/CreativeSpaceIcebreakersGamesForumActivities_215/","title":"Creative Space: Icebreakers, Games & Forum Activities","strap":"Welcome to the Anxiety Support Community! Let us get to know you!"},
{"url":"/forum/AnxietySupport_53/PanicAttacks_49/","title":"Panic Attacks ","strap":"Panic attacks are intense and unpredictable - what are the best ways to overcome them?"},
{"url":"/forum/AnxietySupport_53/SocialAnxietySupportSharing_247/","title":"Social Anxiety Support & Sharing ","strap":"Do you have social anxiety? Find support here!"},
{"url":"/forum/AnxietySupport_53/DailyCheckInThreads_955/","title":"Daily Check-In Threads","strap":"Check-in with the community everyday! Give updates"},
{"url":"/forum/AnxietySupport_53/AnxietyCommunityShoutoutsAppreciations_1842/","title":"Anxiety Community Shout-outs & Appreciations!","strap":"Share the love for your fellow members here!"},
{"url":"/forum/AnxietySupport_53/AnxietyQA_218/","title":"Anxiety Q&A","strap":"Do you have a GENERAL question about Anxiety? Press \"create a new thread\" and Ask it here! For PERSONAL questions, go to Share Your Story!"},
{"url":"/forum/AnxietySupport_53/WelcomesGreetingsandIntroductions_1355/","title":"Welcomes, Greetings and Introductions!","strap":"Post to the monthly cohort thread to say hello and meet others who have joined this month"},
{"url":"/forum/AnxietySupport_53/HealthAnxietySupportForum_668/","title":"Health Anxiety Support Forum","strap":"Share your experiences and thoughts about health-related anxiety!"},
{"url":"/forum/AnxietySupport_53/AnxietyDepressionAMAs_216/","title":"Anxiety (& Depression) AMAs","strap":"Offer your experiences or ask someone a question about Anxiety (& Depression)."},
{"url":"/forum/AnxietySupport_53/Agoraphobia_953/","title":"Agoraphobia ","strap":"A place to share and ask questions about agoraphobia "},
{"url":"/forum/AnxietySupport_53/PhobiasGetsupportforyourphobiahere_250/","title":"Phobias - Get support for your phobia here","strap":"This space is for you to share and find connection. /  If there is a question or topic you'd like addressed, please create a new thread. "},
{"url":"/forum/AnxietySupport_53/AnxietySupportResources_412/","title":"Anxiety Support Resources","strap":"A collation of resources provided by the membership for coping with anxiety and panic attacks"},
{"url":"/forum/AnxietySupport_53/AnxietySupportCommunityTeam_425/","title":"Anxiety Support Community Team","strap":"Learn More About the Anxiety Support Community Team Here :)"},
{"url":"/forum/AnxietySupport_53/PerformanceAnxiety_730/","title":"Performance Anxiety","strap":"School/grades cause anxiety? Work cause anxiety? Sports causing anxiety? Post about it here!"},
{"url":"/forum/AnxietySupport_53/Events_1906/","title":"Events","strap":"Anxiety Support & 7 Cups Events"}]},
{"url":"/home/gratitude/","title":"Positivity & Gratitude","strap":"","forums":[]},
{"url":"/forum/AutismSpectrumDisorderASD_91/","title":"Autism Spectrum Disorder (ASD)","strap":"","forums":[{"url":"/forum/AutismSpectrumDisorderASD_91/NewtotheASDCommunitySayHelloIntroduceYourself_357/","title":"New to the ASD Community - Say Hello & Introduce Yourself!","strap":"We want to get to know you "},
{"url":"/forum/AutismSpectrumDisorderASD_91/IcebreakersGames_1828/","title":"Icebreakers & Games!","strap":"Games, writing prompts and other activities to get to know each other!"},
{"url":"/forum/AutismSpectrumDisorderASD_91/AutismSpectrumDisorderASDCommunityTeam_427/","title":"Autism Spectrum Disorder (ASD) Community Team","strap":"Learn More About the Autism Spectrum Disorder (ASD) Community Team Here :)"},
{"url":"/forum/AutismSpectrumDisorderASD_91/Autism_150/","title":"Autism","strap":"Members or Listeners who have Autism"},
{"url":"/forum/AutismSpectrumDisorderASD_91/ASDInLiteraturePopularCultureandMedia_670/","title":"ASD In Literature, Popular Culture, and Media","strap":"Books and Other Sources: Autism Spectrum Disorder"},
{"url":"/forum/AutismSpectrumDisorderASD_91/Shareyourstruggleshere_356/","title":"Share your struggles here","strap":"What is your story"},
{"url":"/forum/AutismSpectrumDisorderASD_91/FriendsFamilyandLovedOnes_1796/","title":"Friends, Family, and Loved Ones","strap":"For Allies To Ask Questions, Learn, and Share Support!"},
{"url":"/forum/AutismSpectrumDisorderASD_91/SocialTopics_1294/","title":"Social Topics","strap":"Social Experiences and Political Correctness "},
{"url":"/forum/AutismSpectrumDisorderASD_91/ResourcesandInformationonAutism_936/","title":"Resources and Information on Autism","strap":"Share useful resources, knowledge, and other information here."},
{"url":"/forum/AutismSpectrumDisorderASD_91/ASDCheckIns_1791/","title":"ASD Check-Ins.","strap":"Check-in with the community in our team check-in threads!"},
{"url":"/forum/AutismSpectrumDisorderASD_91/AutismAwarenessMonth_1894/","title":"Autism Awareness Month","strap":"This section is to connect with others to promote awareness about ASD & to celebrate Autism Awareness Month!!!"},
{"url":"/forum/AutismSpectrumDisorderASD_91/ASDintheWorkplace_1803/","title":"ASD in the Workplace","strap":"For all things related to autism in a professional setting."}]},
{"url":"/home/bipolar/","title":"Bipolar Support","strap":"","forums":[]},
{"url":"/home/personalitydisorders/","title":"Personality Disorders Support","strap":"The goal of the community is to provide a safe and supportive community for those diagnosed with personality disorders and their loved ones to find the support that they need to help them cope with the affects that the disorders have on their lives through support sessions, the forum, and the feed.","forums":[]},
{"url":"/forum/BullyingSupportCommunity_113/","title":"Bullying Support Community","strap":"","forums":[]},
{"url":"/forum/ChemocareLivingwithRecoveryfromCancerSupport_110/","title":"Chemocare / Living with & Recovery from Cancer Support","strap":"","forums":[{"url":"/forum/ChemocareLivingwithRecoveryfromCancerSupport_110/ChemocareQAHelpfulResources_515/","title":"Chemocare Q & A / Helpful Resources","strap":"Looking for a guide, or have a question you'd like answered? This is the place!"},
{"url":"/forum/ChemocareLivingwithRecoveryfromCancerSupport_110/IntroduceYourselfIcebreakers_516/","title":"Introduce Yourself & Icebreakers","strap":"Get to know people who are going through similar things! You're loved and welcomed here at 7Cups."},
{"url":"/forum/ChemocareLivingwithRecoveryfromCancerSupport_110/Chemocare_517/","title":"Chemocare","strap":"Post anything you'd like here; it's a safe space where we can all come together!"},
{"url":"/forum/ChemocareLivingwithRecoveryfromCancerSupport_110/ChemocareForumTeam_514/","title":"Chemocare Forum Team","strap":"Learn more about the Chemocare Forum Team Here :)"}]},
{"url":"/home/countries/","title":"Around the World","strap":"This is a place where you can: ------> Connect with people from all over the world------> Get and provide support to people from your own country------> Learn about different cultures and perspectives------> Find interesting things about other cultures\n\nJoin us!.","forums":[{"url":"/forum/AroundtheWorld_87/IceBreakersandForumGames_1583/","title":"Ice-Breakers and Forum Games","strap":"Participate in fun icebreakers and games here!"},
{"url":"/forum/AroundtheWorld_87/WeeklyCheckins_1182/","title":"Weekly Check-ins","strap":"Regular check-in threads to let us know how things are going"},
{"url":"/forum/AroundtheWorld_87/Australia_344/","title":"Australia","strap":"Find Connection & Support here!"},
{"url":"/forum/AroundtheWorld_87/CulturalExchangeandDiscussionsinNativeLanguages_379/","title":"Cultural Exchange and Discussions in Native Languages!","strap":"A place to share!"},
{"url":"/forum/AroundtheWorld_87/AroundtheWorldCommunityTeamSpaceUpdatesAnnouncements_1123/","title":"Around the World Community Team Space, Updates & Announcements!","strap":"Around the World Community team pace, updates & announcements!!"},
{"url":"/forum/AroundtheWorld_87/Europe_345/","title":"Europe","strap":"Find Connection & Support here!"},
{"url":"/forum/AroundtheWorld_87/CulturalandInternationalholidaysCelebrations_157/","title":"Cultural and (Inter)national holidays & Celebrations","strap":"Important Days Celebration in your Country ! share it with us here "},
{"url":"/forum/AroundtheWorld_87/Asia_975/","title":"Asia","strap":"Get to know others from Asia here!"},
{"url":"/forum/AroundtheWorld_87/EgyptianMiddleEastCommunity_977/","title":"Egyptian & Middle East Community!","strap":"Get to know others from Egypt & the Middle East here!!"},
{"url":"/forum/AroundtheWorld_87/CountryLeadersandCountryChampionsSubforum_978/","title":"Country Leaders and Country Champions Sub-forum","strap":"Info & updates for country leaders"},
{"url":"/forum/AroundtheWorld_87/NorthSouthAmerica_343/","title":"North & South America","strap":"North & South America connections and cheer!"},
{"url":"/forum/AroundtheWorld_87/ImmigrationandGlobalCitizenship_1283/","title":"Immigration and Global Citizenship!","strap":"A place to talk with immigrants, global citizenship, Migrants, refugees, expats, displaced persons, & diplomats"},
{"url":"/forum/AroundtheWorld_87/WelcomesandIntroductions_1880/","title":"Welcomes and Introductions! ","strap":"Are you new? Introduce yourself to the ATW team! "},
{"url":"/forum/AroundtheWorld_87/AMAAskMeAnything_455/","title":"AMA - Ask Me Anything","strap":"Proud to be an ... (American, Asian, European, etc)"},
{"url":"/forum/AroundtheWorld_87/Africa_998/","title":"Africa","strap":"Meet others from Africa here!"}]},
{"url":"/forum/CurrentEventsDisasterSupport_195/","title":"Current Events & Disaster Support","strap":"","forums":[]},
{"url":"/home/depression/","title":"Depression Support","strap":"We hope that you can find some respite here from what you're going through.","forums":[{"url":"/forum/DepressionSupport_52/DepressionGeneralthreads_30/","title":"Depression General threads ","strap":"Are you dealing with Depression?"},
{"url":"/forum/DepressionSupport_52/DailyCheckinThreads_954/","title":"Daily Check-in Threads","strap":"Depression community check-in & let us know how you are doing today!"},
{"url":"/forum/DepressionSupport_52/Icebreakersandgettingtoknowoneanother_211/","title":" Icebreakers and getting to know one another!","strap":"All Welcome! Welcoming Committee & Fun Found Here."},
{"url":"/forum/DepressionSupport_52/DepressionQA_213/","title":"Depression Q&A ","strap":"Do you have a question about Depression and how you experience depression ? Create a Thread And Ask our Community?"},
{"url":"/forum/DepressionSupport_52/SeasonalAffectiveDisorder_897/","title":"Seasonal Affective Disorder","strap":"Do you experience SAD (seasonal depression)?  Get support here!"},
{"url":"/forum/DepressionSupport_52/IntroduceyourselftotheDepressionCommunity_1357/","title":"Introduce yourself to the Depression Community!","strap":"Post to the monthly introduction thread to introduce yourself and meet others who have joined this month"},
{"url":"/forum/DepressionSupport_52/DepressionSupportSessionsSummaries_535/","title":"Depression Support Sessions & Summaries","strap":"Check here for discussion notes and updates!"},
{"url":"/forum/DepressionSupport_52/DepressionSessionForumActivities_332/","title":"Depression Session Forum Activities","strap":"Weekly Forum Activities assigned to that weeks Depression Session"},
{"url":"/forum/DepressionSupport_52/DepressionResources_214/","title":"Depression Resources ","strap":"Find Resources for Depression Here "},
{"url":"/forum/DepressionSupport_52/TeenDepressionForum_1606/","title":"Teen Depression Forum.","strap":"A place for teens to connect with other teens who live with depression. "},
{"url":"/forum/DepressionSupport_52/TherapistCorner_1288/","title":"Therapist Corner","strap":"A place for tips, info and support from the therapist liaisons"},
{"url":"/forum/DepressionSupport_52/DepressionSupportCommunityLeadershipTeam_404/","title":"Depression Support Community Leadership Team","strap":"Learn More About the Depression Support Community Team Here :)"},
{"url":"/forum/DepressionSupport_52/DepressionSupportSubcommunityFeedTeam_1523/","title":"Depression Support Subcommunity Feed Team","strap":"~ All things feed team ~"},
{"url":"/forum/DepressionSupport_52/WelcomePartyforeveryoneOnlyDepressionSupportSubcommunityP_1199/","title":"Welcome Party for everyone! (Only Depression Support Subcommunity :P)","strap":"26/02/17; 2pm EST; Depression Community Room"},
{"url":"/forum/DepressionSupport_52/AMAsRelatedToDepressionLivingWithDepression_212/","title":"AMA's Related To Depression & Living With Depression ","strap":"Share Your Story Here"},
{"url":"/forum/DepressionSupport_52/HelpWanted_1518/","title":"Help Wanted","strap":"Help wanted within the Depression Support Subcommunity"}]},
{"url":"/home/disabilities/","title":"Disability Support","strap":"","forums":[]},
{"url":"/forum/DomesticAbuseSupportCommunity_121/","title":"Domestic Abuse Support Community","strap":"","forums":[]},
{"url":"/home/eds/","title":"Eating Disorder Support","strap":"","forums":[]},
{"url":"/home/familyandcaregivers/","title":"Family & Caregiver Support","strap":"▪Are you a professional Caregiver?  You are welcome to post here, look for relevant Caregiver threads.","forums":[]},
{"url":"/home/fostercaresupport/","title":"Foster Care Support ","strap":"This community aims to provide support for all those who have had experiences with the foster care system as foster carers, foster kids, transitional age youth, or their supporters!\n\nHave a look around, and join in! Confused about where to start? Click on the 'Check in Today' button and introduce yourself there \n\nTo join our taglist.","forums":[{"url":"/forum/FosterCareSupport_192/IcebreakersandIntroductions_1697/","title":"Icebreakers and Introductions","strap":"Welcome to our Foster Care Community! Please feel free to introduce yourself, and join in with our icebreakers! "},
{"url":"/forum/FosterCareSupport_192/AdoptionandFosterParenting_1514/","title":"Adoption and Foster Parenting","strap":"Share stories and seek support for adoption and foster parenting"},
{"url":"/forum/FosterCareSupport_192/FamilyRelationshipsinFosterCare_1709/","title":"Family Relationships in Foster Care","strap":" Discuss and share about your relationships with your birth family and foster family here!"},
{"url":"/forum/FosterCareSupport_192/InformationPostsandResourcesforFosterKidsParents_1700/","title":"Information Posts and Resources for Foster Kids/Parents","strap":"Please share helpful information and resources here! Just Create a New Thread and share!"},
{"url":"/forum/FosterCareSupport_192/CheckInsHowhaveyoubeen_1699/","title":"Check-Ins: How have you been?","strap":"This is a forum space where you can let us know about how you are feeling and what is going on in your life."},
{"url":"/forum/FosterCareSupport_192/FosterCareCommunityTeam_1698/","title":"Foster Care Community Team","strap":"A central space for all things leader related!"},
{"url":"/forum/FosterCareSupport_192/ShareyourStoryGetSupportHere_1701/","title":"Share your Story! Get Support Here!","strap":"Post your story about foster care and support others going through it."},
{"url":"/forum/FosterCareSupport_192/SupportSystemsinFosterCare_1708/","title":"Support Systems in Foster Care","strap":"A space to discuss the different support systems we experience in foster care!"},
{"url":"/forum/FosterCareSupport_192/TransitionalAgeYouth_1711/","title":"Transitional Age Youth","strap":" Find and share resources for Transitional Age Youth here! Share your stories!"},
{"url":"/forum/FosterCareSupport_192/EventsandAnnouncements_1707/","title":"Events and Announcements","strap":"A space to announce any events happening within the community!"},
{"url":"/forum/FosterCareSupport_192/QuestionsandDiscussion_1710/","title":"Questions and Discussion","strap":" Have any questions about Foster Care? Ask them here, or join another one of the discussions!"}]},
{"url":"/forum/GriefLossCommunity_61/","title":"Grief & Loss Community ","strap":"","forums":[{"url":"/forum/GriefLossCommunity_61/TheLossForum_50/","title":"The Loss Forum","strap":"There are many types of loss, please share yours with us here"},
{"url":"/forum/GriefLossCommunity_61/StagesofGrief_258/","title":"Stages of Grief","strap":"Where do you stand today? "},
{"url":"/forum/GriefLossCommunity_61/GriefLossCommunityTeam_405/","title":"Grief & Loss Community Team","strap":"Learn More About the Grief & Loss Support Community Forum Team Here :)"},
{"url":"/forum/GriefLossCommunity_61/IntroduceYourselftothe7CupsGrieflossCommunity_317/","title":"Introduce Yourself to the 7 Cups Grief & loss Community","strap":"Say hello"},
{"url":"/forum/GriefLossCommunity_61/EulogiesandLetters_1027/","title":"Eulogies and Letters","strap":"Share your euologies or other things you would like to say to those you have lost"},
{"url":"/forum/GriefLossCommunity_61/IcebreakersRelaxation_1849/","title":"Icebreakers & Relaxation","strap":"Lighthearted relief"},
{"url":"/forum/GriefLossCommunity_61/Memories_890/","title":"Memories","strap":"Share memories of your loved ones here"},
{"url":"/forum/GriefLossCommunity_61/SupportingThoseGrieving_1963/","title":"Supporting Those Grieving","strap":"Share how you can support those grieving"},
{"url":"/forum/GriefLossCommunity_61/CopingMechanismsforGrief_1888/","title":"Coping Mechanisms for Grief","strap":"Strategies and mechanisms for coping with grief"},
{"url":"/forum/GriefLossCommunity_61/ProcessingEmotions_257/","title":"Processing Emotions","strap":"Your feelings are valid. Share with us here"},
{"url":"/forum/GriefLossCommunity_61/TheGrieforLossofaChild_893/","title":"The Grief or Loss of a Child","strap":"Share your stories of coping with the loss of a child."},
{"url":"/forum/GriefLossCommunity_61/TheGrieforLossofaFriendorFamilyMember_1443/","title":"The Grief or Loss of a Friend or Family Member","strap":"Have you lost a friend or loved one? Share and get support here"},
{"url":"/forum/GriefLossCommunity_61/Terminations_917/","title":"Terminations","strap":"A place to share our stories and support each other without fear of stigma"},
{"url":"/forum/GriefLossCommunity_61/Suicides_1991/","title":"Suicides","strap":"Post about your grief or loss of someone to suicide"},
{"url":"/forum/GriefLossCommunity_61/TheGrieforLossofaPet_1962/","title":"The Grief or Loss of a Pet","strap":"Share your stories of coping with the loss of a pet"}]},
{"url":"/home/groupmod/","title":"Group Support","strap":"","forums":[]},
{"url":"/home/healthyliving/","title":"Healthy Living Support","strap":"Welcome, friends, to the Healthy Living Support Online Community at 7 Cups of Tea.","forums":[]},
{"url":"/home/helpwanted/","title":"Help Wanted","strap":"","forums":[]},
{"url":"/home/hobbyzone/","title":"Hobby Zone","strap":"Here you can discover and explore therapeutic hobbies for healing.","forums":[]},
{"url":"/home/IndianSupport/","title":"Namaste India","strap":"Welcome, friends, to the Namaste India Online Community at 7 Cups of Tea.","forums":[]},
{"url":"/forum/JobandCareerSupportCommunity_158/","title":"Job and Career Support Community","strap":"","forums":[{"url":"/forum/JobandCareerSupportCommunity_158/EmergencyMedicalPersonnelSupport_1978/","title":"Emergency & Medical Personnel Support","strap":"Support for those who work in the emergency and medical professions"},
{"url":"/forum/JobandCareerSupportCommunity_158/UnemploymentSupport_1001/","title":"Unemployment Support","strap":"Struggling with unemployment?  Let us support you here!"},
{"url":"/forum/JobandCareerSupportCommunity_158/TellUsAboutYourJob_1003/","title":"Tell Us About Your Job!","strap":"Tell us about what you do, and connect with others in your profession!"},
{"url":"/forum/JobandCareerSupportCommunity_158/CelebrationCorner_1004/","title":"Celebration Corner","strap":"New job? Big promotion? Project went well? Celebrate with us!"},
{"url":"/forum/JobandCareerSupportCommunity_158/WorkandCareerResources_1005/","title":"Work and Career Resources","strap":"Share useful resources for managing work stress, finding jobs, or general career support!"},
{"url":"/forum/JobandCareerSupportCommunity_158/JobSearching_1002/","title":"Job Searching","strap":"Looking for work?  Share stories, tips, and ask questions here!"},
{"url":"/forum/JobandCareerSupportCommunity_158/WorkStress_1000/","title":"Work Stress","strap":"Work stressing you out? Struggling at a job? Tell us about it here!"},
{"url":"/forum/JobandCareerSupportCommunity_158/CoworkerRelationships_1532/","title":"Coworker Relationships","strap":"Do you have good relationships with your coworkers? Any that are tough? Tell us more here!"},
{"url":"/forum/JobandCareerSupportCommunity_158/StartupSupport_1592/","title":"Startup Support","strap":"Share your experiences, successes, and struggles in starting a new company"},
{"url":"/forum/JobandCareerSupportCommunity_158/JobSupportCommunityForumTeam_1006/","title":"Job Support Community Forum Team","strap":"Learn More About the Job Support Community Team Here :)"}]},
{"url":"/home/office/","title":"Kitchen Table","strap":"We ask you to gather around the kitchen table with us for the purpose of learning, sharing, collaborating and building community together.","forums":[]},
{"url":"/home/lgbtq/","title":"LGBTQ+ / MOGII Support","strap":"","forums":[]},
{"url":"/forum/LonelinessSupportCommunity_78/","title":"Loneliness Support Community","strap":"","forums":[{"url":"/forum/LonelinessSupportCommunity_78/ShareYourStory_1436/","title":"Share Your Story","strap":"Feel free to share your story, or stories, of loneliness here!\t\t"},
{"url":"/forum/LonelinessSupportCommunity_78/IcebreakersWritingPrompts_1534/","title":"Icebreakers & Writing Prompts","strap":"Want to get to know other sub-community members? Join the threads here, and make some friends.\t\t"},
{"url":"/forum/LonelinessSupportCommunity_78/LetsfeellonelytogetherINPROGRESS_311/","title":"Let's feel lonely together - IN PROGRESS","strap":"Share here"},
{"url":"/forum/LonelinessSupportCommunity_78/CommunityLeadershipAnnouncements_1752/","title":"Community Leadership & Announcements","strap":"Meet the sub-community team, and keep a look out for sub-community updates here."},
{"url":"/forum/LonelinessSupportCommunity_78/CopingWithLoneliness_599/","title":"Coping With Loneliness","strap":"If you’re finding it difficult to cope with loneliness, or have any tips or tricks, you’ve come to the right place.\t\t"},
{"url":"/forum/LonelinessSupportCommunity_78/SupportResources_689/","title":"Support & Resources","strap":"Looking for support with Loneliness? Check here for resources that other people have shared!\t\t"},
{"url":"/forum/LonelinessSupportCommunity_78/WelcomeIntroductions_1437/","title":"Welcome & Introductions","strap":"New to the loneliness support community? Introduce yourself here.\t\t"},
{"url":"/forum/LonelinessSupportCommunity_78/CommunityEventsCelebrations_705/","title":"Community Events & Celebrations","strap":"All official past, present and future community evens, relating to loneliness, and celebrations can be found here."},
{"url":"/forum/LonelinessSupportCommunity_78/LonelinessinRuralCommunities_1794/","title":"Loneliness in Rural Communities ","strap":"Loneliness in Rural Communities "},
{"url":"/forum/LonelinessSupportCommunity_78/ForumDiscussions_1440/","title":"Forum Discussions","strap":"Official Forum discussions, led by the loneliness support forum team, can be found here."},
{"url":"/forum/LonelinessSupportCommunity_78/CommunityCheckins_1435/","title":"Community Check-ins","strap":"Official check-ins will be posted in this sub-forum by our awesome team members."}]},
{"url":"/home/mindfulness/","title":"Mindfulness Center","strap":"The Mindfulness Center welcomes you to a place where it is okay to just be, and not worry about 100 things.","forums":[{"url":"/forum/MindfulnessCenter_106/IceBreakerLake_1948/","title":"Ice Breaker Lake","strap":"Here is where we \"break the ice\" - get to know each other asking questions or sharing a picture"},
{"url":"/forum/MindfulnessCenter_106/DailyCheckIns_1263/","title":"Daily Check-Ins","strap":"Share your thoughts and experiences with mindfulness"},
{"url":"/forum/MindfulnessCenter_106/MindfulnessAndTeens_1877/","title":"Mindfulness And Teens","strap":"Teen Area"},
{"url":"/forum/MindfulnessCenter_106/CreativeMoments_1387/","title":"Creative Moments","strap":"Share your creativity"},
{"url":"/forum/MindfulnessCenter_106/MindfulnessQandAs_1381/","title":"Mindfulness Q and A's","strap":"Here you can ask any questions or share on concerns"},
{"url":"/forum/MindfulnessCenter_106/ComeoninandsayhitotheMindfulnessCommunity_1362/","title":"Come on in and say \"hi\" to the Mindfulness Community","strap":"Come in and say \"hi\" to others who enjoy mindfulness"},
{"url":"/forum/MindfulnessCenter_106/LisasNookMindfulnessLiaisonTherapist_1905/","title":"Lisa's Nook (Mindfulness Liaison Therapist)","strap":"Please share your questions for Lisa or your stories"},
{"url":"/forum/MindfulnessCenter_106/InteractiveCommunityDiscussions_508/","title":"Interactive Community Discussions","strap":"Post here on your discussion you are having OR create a forum discussion for the community"},
{"url":"/forum/MindfulnessCenter_106/MindfulnessPracticesSkills_490/","title":"Mindfulness Practices/Skills","strap":"Share your ideas, skills/practices that help you with Mindfulness"},
{"url":"/forum/MindfulnessCenter_106/TeamAnnouncements_1365/","title":"Team Announcements ","strap":"This area team leaders will post any adding or changing that will be happening"},
{"url":"/forum/MindfulnessCenter_106/BuddyUpCornerCLOSED_1718/","title":"Buddy Up Corner(CLOSED)","strap":"Welcome Buddies! Here is your own space. Encourage each other, share on mindfulness skills, create forum threads together. etc"},
{"url":"/forum/MindfulnessCenter_106/SelfCareDiariesAndChallenges_1674/","title":"Self Care Diaries And Challenges ","strap":"Please share if you are going on self care break/coming back or need encouragement on how to self care more"},
{"url":"/forum/MindfulnessCenter_106/MindfulnessAndDBTGroundingSkills_1455/","title":"Mindfulness And DBT/Grounding Skills","strap":"In this area share on DBT/Grounding skills that relate to mindfulness"},
{"url":"/forum/MindfulnessCenter_106/MindfulnessAppreciationShoutOutsToCommunity_1786/","title":"Mindfulness Appreciation Shout Outs To Community","strap":"In this area I will be adding the shout outs the community has for everyone."},
{"url":"/forum/MindfulnessCenter_106/ResourceLibrary_1062/","title":"Resource Library","strap":"Training resources by Mindfulness team - please do NOT post in Resources. Instead post in other threads https://www.7cups.com/forum/MindfulnessSupport"}]},
{"url":"/home/nami/","title":"NAMI","strap":"","forums":[]},
{"url":"/forum/OCDBFRBCommunity_165/","title":"OCD / BFRB Community","strap":"","forums":[]},
{"url":"/home/parentingandpregnancy/","title":"Parenting & Pregnancy Support","strap":"","forums":[]},
{"url":"/home/poc/","title":"Young People of Color","strap":"Everyone (irrespective of background) is welcome to share and participate in the Young People of Color Community.","forums":[{"url":"/forum/YoungPeopleofColor_129/ForumDiscussionsandQA_703/","title":"Forum Discussions and Q & A","strap":"Questions and discussions on articles and various other topics."},
{"url":"/forum/YoungPeopleofColor_129/WelcomesandIntroductions_1548/","title":"Welcomes and Introductions","strap":"Stop by, say hi and introduce yourself to the People of Color Support community."},
{"url":"/forum/YoungPeopleofColor_129/PeopleofColorSupportCommunityTeam_1152/","title":"People of Color Support Community Team","strap":"Learn more about the POC Community Team here!"},
{"url":"/forum/YoungPeopleofColor_129/IcebreakersandForumGames_1749/","title":"Icebreakers and Forum Games","strap":"Icebreakers, Games and Forum Activities here."},
{"url":"/forum/YoungPeopleofColor_129/YPOCCheckIns_1753/","title":"YPOC: Check-Ins","strap":"People of Color Support Weekly Check-Ins"},
{"url":"/forum/YoungPeopleofColor_129/TheYPOCRoundtable_1919/","title":"The YPOC Roundtable","strap":"Scenarios on different topics and discussions."},
{"url":"/forum/YoungPeopleofColor_129/TeenSupportCommunity_1058/","title":"Teen Support Community","strap":"Are you a teen? This is the place for you!"},
{"url":"/forum/YoungPeopleofColor_129/CommunityUpdatesEventsShoutoutsCelebrations_1477/","title":"Community Updates, Events, Shout outs & Celebrations!","strap":"Includes information regarding POC sub-community events."},
{"url":"/forum/YoungPeopleofColor_129/MentalHealthSelfCare_1927/","title":"Mental Health & Self-Care ","strap":"Fun and Interactive Activities for Forum and Feed."},
{"url":"/forum/YoungPeopleofColor_129/YPOCFAQInformation_702/","title":"YPOC FAQ / Information","strap":"Ask questions about topics to do with PoC and learn more"},
{"url":"/forum/YoungPeopleofColor_129/ShareYourStoryPeopleofColorExperiencesinEverydayLife_700/","title":"Share Your Story: People of Color Experiences in Everyday Life","strap":"Let us know your experiences and get some support!"},
{"url":"/forum/YoungPeopleofColor_129/YPOCForumActivities_701/","title":"YPOC Forum Activities ","strap":"This is a section dedicated to providing information about upcoming discussions and related forum activity"},
{"url":"/forum/YoungPeopleofColor_129/YPOCCommunityResources_1761/","title":"YPOC Community: Resources","strap":"Seek or share helpful resources directly related to helping people of color."}]},
{"url":"/home/projectsandevents/","title":"Community Projects & Events","strap":"In our resources section you can find application links and the leaders of each community.","forums":[]},
{"url":"/forum/PsychotherapyandPsychotherapeuticApproachesDiscussionsInformation_97/","title":"Psychotherapy and Psychotherapeutic Approaches : Discussions & Information","strap":"","forums":[]},
{"url":"/home/relationships/","title":"Relationship & Friendship Support","strap":"Connect.","forums":[{"url":"/forum/RelationshipFriendshipSupport_66/BeingSingle_1550/","title":"Being Single!!","strap":"Share stories, ask questions and get support here!! "},
{"url":"/forum/RelationshipFriendshipSupport_66/UnconventionalRelationships_529/","title":"Unconventional Relationships","strap":"Long Distance Relationships, Open Relationships, Swingers, Friends With Benefits- And The Like"},
{"url":"/forum/RelationshipFriendshipSupport_66/IntroductionsIcebreakersFun_1256/","title":"Introductions, Icebreakers & Fun!!","strap":"Welcome to Relationship Support! Let's get to know each other & have some fun time!! "},
{"url":"/forum/RelationshipFriendshipSupport_66/RomanticRelationships_255/","title":"Romantic Relationships","strap":"Find support on how to best manage romantic relationships here. "},
{"url":"/forum/RelationshipFriendshipSupport_66/Friendships_256/","title":"Friendships","strap":"Managing our friendships! Find support here! If your topic is not addressed yet, \"create a new thread\" to share!"},
{"url":"/forum/RelationshipFriendshipSupport_66/ForumDiscussionCorner_1161/","title":"Forum Discussion Corner","strap":"A place for forum discussions over different aspects of different relationships!"},
{"url":"/forum/RelationshipFriendshipSupport_66/CheckinsThread_1452/","title":"Check-ins Thread!!","strap":"A place for us to take a moment and share what is going on and how we are doing."},
{"url":"/forum/RelationshipFriendshipSupport_66/RelationshipsTools_526/","title":"Relationships Tools","strap":"A place to find resources to get help for yourself and relationships. "},
{"url":"/forum/RelationshipFriendshipSupport_66/Shareyourstory_1034/","title":"Share your story","strap":"Share your challenges and let's discuss and figure out together. "},
{"url":"/forum/RelationshipFriendshipSupport_66/BreakupsDivorce_1031/","title":"Breakups & Divorce","strap":"Going through or recently been through a break up/divorce? Considering a divorce/break-up? Tell us here. "},
{"url":"/forum/RelationshipFriendshipSupport_66/AMAsSpecialEventsinRelationshipSupport_1191/","title":"AMA's & Special Events in Relationship Support!","strap":"AMA's & Special Events in Relationship Support!"},
{"url":"/forum/RelationshipFriendshipSupport_66/ALetterToMyEx_1036/","title":"A Letter To My Ex","strap":"Write a letter to your ex to vent your pain and frustrations"},
{"url":"/forum/RelationshipFriendshipSupport_66/RelationshipCommunityTeam_1213/","title":"Relationship Community Team!! ","strap":"Learn More About Relationship Community Leadership & Moderation Team & Updates Here"},
{"url":"/forum/RelationshipFriendshipSupport_66/TherapistCorner_1623/","title":"Therapist Corner","strap":"A place for AskMeAnything to therapist over different topics of Relationship."},
{"url":"/forum/RelationshipFriendshipSupport_66/HowToSupport_1883/","title":"How To Support ","strap":"Learn more how to support someone (suffering from mental health issues) in romantic / non-romantic relationships. "},
{"url":"/forum/RelationshipFriendshipSupport_66/TeensOnlyZoneRelationshipsFriendships_1789/","title":"Teens Only Zone: Relationships & Friendships! ","strap":"A safe space for teens to discuss issues and share helpful information regarding relationships and friendships!"}]},
{"url":"/home/safe7cups/","title":"Safety & Knowledge at 7 Cups","strap":"Here at Safety & Knowledge, our focus is on creating a culture of awareness and support.","forums":[{"url":"/forum/SafetyKnowledgeat7Cups_181/QuestionsfromthecommunityAnsweredDiscussedhere_36/","title":"Questions from the community! Answered & Discussed here","strap":"Ask questions and get answers from admins and forum moderators."},
{"url":"/forum/SafetyKnowledgeat7Cups_181/SafetyPatrolTeam_1685/","title":"Safety Patrol Team","strap":"Announcements, discussions, questions, and check-ins."},
{"url":"/forum/SafetyKnowledgeat7Cups_181/Guidesonhowtomanagesituationson7cups_1059/","title":"Guides on how to manage situations on 7 cups! ","strap":"Use this forum to post threads and resources to help other uses navigate 7 Cups"},
{"url":"/forum/SafetyKnowledgeat7Cups_181/TeenSafety_1677/","title":"Teen Safety","strap":"A place for teen-specific discussions and coverage."},
{"url":"/forum/SafetyKnowledgeat7Cups_181/CommunityModeratorWeeklySchedule_1640/","title":"Community Moderator Weekly Schedule","strap":"H's Active Duty Shifts Posted Here!"},
{"url":"/forum/SafetyKnowledgeat7Cups_181/UpcomingSafetyDiscussions_1737/","title":"Upcoming Safety Discussions","strap":"Upcoming Safety Discussions"},
{"url":"/forum/SafetyKnowledgeat7Cups_181/WelcometoSafetyKnowledgeIntroduceyourself_1662/","title":"Welcome to Safety & Knowledge / Introduce yourself!","strap":"Welcome!"},
{"url":"/forum/SafetyKnowledgeat7Cups_181/WeeklyCheckIns_1682/","title":"Weekly Check-Ins","strap":"Daily check-ins here"},
{"url":"/forum/SafetyKnowledgeat7Cups_181/PracticeSituationsWhattodowhen_1369/","title":"Practice Situations - What to do when!","strap":"Here we will post practice situations"},
{"url":"/forum/SafetyKnowledgeat7Cups_181/7CupsSafetyToolsReportFormsMore_1371/","title":"7 Cups Safety Tools, Report Forms & More!","strap":"7 Cups Safety Tools, Report Forms & More!"},
{"url":"/forum/SafetyKnowledgeat7Cups_181/ConflictResolutionQuestionshowtosandmore_1372/","title":"Conflict Resolution - Questions, how-to's and more! ","strap":"Conflict Resolution - Questions, how-to's and more! "},
{"url":"/forum/SafetyKnowledgeat7Cups_181/CommunityGuidelines_1374/","title":"Community Guidelines ","strap":"Information on community guidelines and guideline updates announced here"},
{"url":"/forum/SafetyKnowledgeat7Cups_181/GeneralConversations_1625/","title":"General Conversations ","strap":"Conversations about safety and quality on 7 Cups"},
{"url":"/forum/SafetyKnowledgeat7Cups_181/KeepingyourselfsafeAnnouncements_1373/","title":"Keeping yourself safe - Announcements","strap":"Keeping yourself safe - Announcements"},
{"url":"/forum/SafetyKnowledgeat7Cups_181/Emergency_346/","title":"Emergency","strap":"If you have taken something or tried to commit suicide please do consider the following options."},
{"url":"/forum/SafetyKnowledgeat7Cups_181/SpecialSafetyProjects_1634/","title":"Special Safety Projects ","strap":"Special Safety Projects "},
{"url":"/forum/SafetyKnowledgeat7Cups_181/SafetyChallengesandEvents_1713/","title":"Safety Challenges and Events","strap":"Safety Challenges and Events"},
{"url":"/forum/SafetyKnowledgeat7Cups_181/InternetBullyingSupportinformation_1370/","title":"Internet Bullying Support & information","strap":"Bullying is not okay. Here we will share resources on how to prevent bullying on 7 cups and the internet"}]},
{"url":"/forum/SchizophreniaandPsychoticDisordersSupport_105/","title":"Schizophrenia and Psychotic Disorders Support","strap":"","forums":[]},
{"url":"/home/selfharm/","title":"Self-Harm Recovery","strap":"It’s great to have you here and we are proud of you for making the first brave step in reaching out for support by joining us in this supportive, safe, friendly environment.","forums":[{"url":"/forum/SelfHarmRecovery_65/IntroduceYourselfIcebreakers_253/","title":"Introduce Yourself & Icebreakers ","strap":"Get to know our self-harm recovery community & share a bit about you!"},
{"url":"/forum/SelfHarmRecovery_65/CheckinThreads_1284/","title":"Check-in Threads","strap":"Check in with the community!"},
{"url":"/forum/SelfHarmRecovery_65/DiscussionArea_1306/","title":"Discussion Area","strap":"A place to learn and discuss anything related to self-harm"},
{"url":"/forum/SelfHarmRecovery_65/SelfHarm_45/","title":"Self-Harm ","strap":"It can be a way to help you cope with problems. Use this as a place to share your experiences and helpful resources on self-harm. "},
{"url":"/forum/SelfHarmRecovery_65/GoalsandSuccessCorner_1394/","title":"Goals and Success Corner ","strap":"Share your goals and successes with the community"},
{"url":"/forum/SelfHarmRecovery_65/SupportingaSelfHarmer_1311/","title":"Supporting a Self-Harmer","strap":"A place for people to find support while trying to support someone who self-harms"},
{"url":"/forum/SelfHarmRecovery_65/RecoveryZone_1305/","title":"Recovery Zone ","strap":"Share your recovery tips and your journey to recovery with the community!"},
{"url":"/forum/SelfHarmRecovery_65/SelfHarmRecoveryCommunityTeam_413/","title":"Self-Harm Recovery Community Team","strap":"Leaders assemble! Get meeting transcripts, future plans and ideas, all here!"},
{"url":"/forum/SelfHarmRecovery_65/MonthlyWelcomeThreads_1604/","title":"Monthly Welcome Threads","strap":"These threads are for new members of the self-harm recovery community to say hi and introduce themselves!"},
{"url":"/forum/SelfHarmRecovery_65/CreativeCorner_1412/","title":"Creative Corner","strap":"Time to get creative! Got any poems or artwork you made? Show us here!"},
{"url":"/forum/SelfHarmRecovery_65/MeetTheTeam_1966/","title":"Meet The Team","strap":"Here you will be able to meet our new team members, say hello to them & read a short description of them! "},
{"url":"/forum/SelfHarmRecovery_65/SupportArea_1845/","title":"Support Area","strap":"A supportive area to share things about you and to discuss with others your struggles"},
{"url":"/forum/SelfHarmRecovery_65/DistractionZone_1424/","title":"Distraction Zone","strap":"A place for fun and games to distract you from urges!"},
{"url":"/forum/SelfHarmRecovery_65/SelfHarmQA_260/","title":"Self-Harm Q&A","strap":"Do you have a self-harm question? Press \"create a new thread\" and add it here. "},
{"url":"/forum/SelfHarmRecovery_65/InformationandResources_1079/","title":"Information and Resources","strap":"Share resources for self harm, coping mechanisms, and other information here"},
{"url":"/forum/SelfHarmRecovery_65/Events_1350/","title":"Events","strap":"Find out about the latest events in the Self-Harm Recovery subcommunity here!"},
{"url":"/forum/SelfHarmRecovery_65/Offtopic_1665/","title":"Off-topic","strap":"Post things here that don't fit anywhere else!"},
{"url":"/forum/SelfHarmRecovery_65/RecoveryBuddies_1510/","title":"Recovery Buddies ","strap":"A place for recovery buddies to connect and get updates! "}]},
{"url":"/forum/SexualHealth_49/","title":"Sexual Health","strap":"","forums":[]},
{"url":"/home/siteupdates/","title":"Site Updates","strap":"Subscribe to keep up to date with the latest 7 Cups features and site updates!!.","forums":[]},
{"url":"/home/students/","title":"Student Support","strap":"","forums":[]},
{"url":"/home/teenbodyimage/","title":"Teen Self-Esteem & Body Image","strap":"The Teen Self-Esteem and Body Image (TSEBI) community is a teen-only space where you can connect with other peers about self-esteem and body image topics.","forums":[{"url":"/forum/TeenSelfEsteemBodyImage_190/WeeklyCheckIns_1659/","title":"Weekly Check-Ins","strap":"Teen Self-Esteem & Body Image community check-in & let us know how you are doing today!"},
{"url":"/forum/TeenSelfEsteemBodyImage_190/StrugglingWithBodyImage_1660/","title":"Struggling With Body Image ","strap":"Space to receive support if you're struggling with body image"},
{"url":"/forum/TeenSelfEsteemBodyImage_190/SelfConfidenceCorner_1715/","title":"Self-Confidence Corner ","strap":"A safe space to ask for help or get support for building self-confidence! "},
{"url":"/forum/TeenSelfEsteemBodyImage_190/YourJourney_1772/","title":"Your Journey","strap":"A place to share your self-esteem and body image journey. You can share what helped you, how you have been coping up with various challenges. Be YOU!"},
{"url":"/forum/TeenSelfEsteemBodyImage_190/SelfEsteemSupport_1658/","title":"Self-Esteem Support ","strap":"A place for teens to connect on self-esteem issues."},
{"url":"/forum/TeenSelfEsteemBodyImage_190/WelcomeIcebreakers_1667/","title":"Welcome & Icebreakers!","strap":"Welcome & Icebreakers!"},
{"url":"/forum/TeenSelfEsteemBodyImage_190/LeadershipCommunityDevelopmentUpdates_1666/","title":"Leadership & Community Development Updates!","strap":"Leadership & Community Development Updates!"},
{"url":"/forum/TeenSelfEsteemBodyImage_190/MembersShareyourStory_1788/","title":"Members: Share your Story! ","strap":"This space is reserved for member threads! Create a thread & get support! Members & listeners can reply to your posts * 7Cups forum guidelines apply*"},
{"url":"/forum/TeenSelfEsteemBodyImage_190/PersonalCorner_1922/","title":"Personal Corner","strap":"A place designed for all of YOU! You can use this as your own personal place to list down things you are grateful for, your accomplishments, etc."},
{"url":"/forum/TeenSelfEsteemBodyImage_190/JournalPrompts_1751/","title":"Journal Prompts","strap":"A cool way to express yourself & connect with other teens! "},
{"url":"/forum/TeenSelfEsteemBodyImage_190/TSEBICommunityEventsForumGames_1692/","title":"TSEBI Community Events & Forum Games","strap":"This is a fun space for posting about TSEBI community events & forums games!"},
{"url":"/forum/TeenSelfEsteemBodyImage_190/PositiveBodyImageSupport_1197/","title":"Positive Body Image Support","strap":"Body Image can be challenging as a teen! let's talk about it and support one another"},
{"url":"/forum/TeenSelfEsteemBodyImage_190/ResourcesforSelfEsteemBodyImageTopics_1712/","title":"Resources for Self-Esteem & Body Image Topics ","strap":"Please share helpful self-esteem & body image resources here! Just Create a New Thread and share!"},
{"url":"/forum/TeenSelfEsteemBodyImage_190/SelfEsteemBodyImageQA_1736/","title":"Self-Esteem & Body Image Q&A","strap":"Do you have a question about Self-Esteem or Body Image? Create a Thread And Ask our Community!"}]},
{"url":"/home/teens/","title":"Teen Only Zone","strap":"Welcome, friends, to the Teen Only Zone Online Community at 7 Cups of Tea.","forums":[{"url":"/forum/TeenOnlyZone_123/TeenCommunityIntroductions_621/","title":"Teen Community Introductions","strap":"Say hello, welcome new teens, break some ice!"},
{"url":"/forum/TeenOnlyZone_123/IceBreakersWritingPrompts_1116/","title":"Ice Breakers &  Writing Prompts","strap":"Fun Games, writing prompts and other cool ways to get to know each other."},
{"url":"/forum/TeenOnlyZone_123/ShareYourStory_1552/","title":"Share Your Story","strap":"Tell us about your issue - we're all here to help you!"},
{"url":"/forum/TeenOnlyZone_123/TeenZoneWeeklyCheckIns_1286/","title":"Teen Zone Weekly Check-Ins","strap":"A place for the Teen Zone’s official weekly check-in threads!"},
{"url":"/forum/TeenOnlyZone_123/ImaTeenandIstrugglewith_1160/","title":"“I’m a Teen, and I struggle with...”","strap":"This is a safe place for you to express how your issues feel to you and how being a teenager impacts them. "},
{"url":"/forum/TeenOnlyZone_123/TheOldieCorner_1473/","title":"The Oldie Corner","strap":"For Adult-Teen Listeners to connect with Teens! "},
{"url":"/forum/TeenOnlyZone_123/BullyingPeerPressure_1169/","title":"Bullying & Peer Pressure ","strap":"Here's a place to share share your stories of bullying & peer pressure, get help and share your support!"},
{"url":"/forum/TeenOnlyZone_123/SocialAwareness_1901/","title":"Social Awareness","strap":"A place to share all your social concerns and comments! "},
{"url":"/forum/TeenOnlyZone_123/SelfCareCorner_1243/","title":"Self-Care Corner","strap":"How do you practice self-care? Share ideas, inspirational quotes, and more!"},
{"url":"/forum/TeenOnlyZone_123/TeenLeadersSubcommunity_1556/","title":"Teen Leaders & Subcommunity!","strap":"Information on new teen leaders, applications & everything about TOZ!"},
{"url":"/forum/TeenOnlyZone_123/TeenCMStation_590/","title":"Teen CM Station","strap":"News, Updates, thoughts and other 7cups related things from our Teen Community Manager to the world!"},
{"url":"/forum/TeenOnlyZone_123/Forumdiscussions_1655/","title":"Forum discussions","strap":"This is a great place for engaging posts and to hold discussions within our forums!"},
{"url":"/forum/TeenOnlyZone_123/WhenGrowingUp_623/","title":"When Growing Up","strap":"Need support or have doubts about growing up? Post here to connect with others"},
{"url":"/forum/TeenOnlyZone_123/CopingSkillsSupport_1933/","title":"Coping Skills Support","strap":"Grow your coping skills!"},
{"url":"/forum/TeenOnlyZone_123/EventsForTeens_1546/","title":"Events For Teens","strap":"Post here about events that are specific to teens or post and link to other events on the site. "}]},
{"url":"/forum/ThinkingSpace_130/","title":"Thinking Space","strap":"","forums":[]},
{"url":"/home/trauma/","title":"Trauma Support","strap":"The Trauma Support Community aims to provide a safe, empowering, inclusive, supportive & proactive community for Survivors of Trauma to have the opportunity to begin healing from their experiences, in a nonjudgmental environment through support sessions, posts and feeds.","forums":[]},
{"url":"/home/veterans/","title":"Veterans & Military Support","strap":"","forums":[]}]
